### ISSUE TITLE
Add to ROMManager

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#110]
I would like to get my Spice MI700/Commtiva Link N700/Viewpad 7 listed..Thanks
    {
        init: "init.qcom.rc",
        key: "FM6",
        name: "Spice MI700, Commtiva Link N700 and more)",
        version: "2.5.1.2"
        alternate_recovery:
        {
            name: "MI700 Recovery v1.6",
            url: "http://dl.dropbox.com/u/15816725/MI700-recovery-V1_3.img"
        }
    }

git://github.com/hucqim80/ROMManagerManifest.git 
devices.js

**Comment by pcmac77** [comment]
done, and corrected a comma goof
