### ISSUE TITLE
add manifest

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#112]
can you add my manifest to rom manager, thanks
https://github.com/jamezelle/ROM-Manager-Manifest

EDIT: it seems you already have my developer manifest for the eris can you just remove that  and add this new one supporting the eris and sholes, thanks for your time.

```
    developer: "Jamezelle",
    id: "jamezelle",
    summary: "ROMS for the Droid and Droid Eris!",
    manifest: "http://github.com/jamezelle/ROM-Manager-Manifest/raw/master/manifest.js",
    free: true,
    roms:
    {
        desirec: true,
        sholes: true
    }
```

**Comment by pcmac77** [comment]
done
