### ISSUE TITLE
not loading rom list from github 

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#113]
i have my rom list (manifest.js) hosted here on github, 

here is a logcat of "Error occurred while downloading the ROM list!" error

http://pastebin.com/vmmhxgvW

also here is a direct link to the manifest which is what rom manager is trying to load:

https://github.com/jamezelle/ROM-Manager-Manifest/raw/master/manifest.js

Any help is appreciated, thanks!

EDIT: I'm going to guess and say this is an ssl issue? if so i can upload the manifest elsewhere. can anyone confirm this to be an ssl issue?

**Comment by pcmac77** [comment]
I see a number of missing commas.  You need to use valid javascript syntax.

Hope this helps.

Peter

**Comment by ghost** [comment]
Thanks Peter for your help today/yesterday, I rewrote the manifest based on the samplemanifest.js . I am now hosting the manifest non-ssl secure so hopefully this will work now. 

Here is the _perminant_ link to the manifest.js . 

http://www.jamezelle.com//RomManagerManifest/manifest.js

Again thanks for your time in helping with this.

--Jamezelle

**Comment by pcmac77** [comment]
Hi Jamezelle,

No problem.  I'm glad to help.  In your updated manifest, I spotted a dangling comma just after the end of the curly brace (line #30).  It should be removed.  I don't think I see anything else.

Good luck.

Peter

**Comment by ghost** [comment]
Removed the comma, 

http://jamezelle.com/RomManagerManifest/manifest.js

thats the perminant link, if you could add that for me, thanks!

**Comment by pcmac77** [comment]
Jamezelle,

Please also make a developer section which will to be added to the master manifest.  You can follow the sample found here: https://github.com/koush/ROMManagerManifest/blob/gh-pages/samples/developer.js

**Comment by ghost** [comment]
here is my devlepor manifest

http://jamezelle.com/RomManagerManifest/jamezelle.js

**Comment by pcmac77** [comment]
Sorry, looks like I had already added your developer section to the manifest.  I've just updated the link to your to your manifest: http://jamezelle.com/RomManagerManifest/manifest.js.

Peter

**Comment by ghost** [comment]
Thanks for everything Peter, works well.
