### ISSUE TITLE
ROM MAnager should check for the existence of the update files before booting into recovery

### ISSUE THREAD

**Issue by fearphage** [koush/ROMManagerManifest#115]
## Steps to repro:
1. Download a ROM (and gapps if applicable)
2. Cancel the screen to backup and wipe everything
3. Press menu and choose "Clear Download Cache"
4. Select the "Download Complete" notification from the notification area
5. Confirm that you want to backup or wipe data/cache (I'd leave both blank for speed)
## Expected result:

ROM Manager says "Hey, there is nothing to update to. I can't find [SPECIFIED ROM].zip so I won't reboot into recovery."
## Actual:

ROM Manager reboots to recover and performs backup and data/cache wipe as requested and then when it's time to flash the ROM from the nonexistent files, it throws an error (can't open zip or something).

**Comment by koush** [comment]
Ahh good bug. ROM Manager does actually check the validity of zip files, after they have been downloaded. I'll see if I can get this fix in.

**Comment by koush** [comment]
But there will always be a race condition: the file can always be deleted between the request to restart and the restart. The fix would just make it less likely that it happens :P

**Comment by fearphage** [comment]
Well less like is good. As long as it checks that the files are there, before initializing reboot to recover, I can live with the edge case/race condition that it is removed between those 2 events. Another plan of attack is perhaps to check for the files in recovery mode before you carry out the other tasks. Perhaps both should be implemented?

**Comment by fearphage** [comment]
I think the real issue is the ROM Manger is downloading the files. ROM Manager removes the files and then ROM Manager is caught off guard when the files it removed are missing. You don't have to take into account external apps. You will know that ROM Manager didn't remove the files it's about to try to install.

**Comment by koush** [comment]
That's true; ROM Manager should definitely be responsible for managing it's own files wisely. 
Thanks again!

**Comment by fearphage** [comment]
No, thank you.
