### ISSUE TITLE
add my ROM to ROM Manager?

### ISSUE THREAD

**Issue by davidjr621** [koush/ROMManagerManifest#116]
Could you guys please add my ROM into ROM Manager?
My Manifest - http://db.tt/CzYWHOT
Dev Manifest - http://db.tt/QpzKOra

Thanks,
-davidjr621

**Comment by pcmac77** [comment]
I just added your dev section to manifest.js.  Please note, however, that your manifest at http://dl.dropbox.com/u/9372031/Axiom/axiom.js is not properly structured, and will not be parsed properly by ROM Manager.

Peter

**Comment by pcmac77** [comment]
There's at least a dangling comma and unmatched curly braces.  Just look at the end of the file for starters.

Peter
