### ISSUE TITLE
Themed CyanogenMod for ROM Manager

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#12]
Hi,

I was wondering if I could get my themed ROM onto ROM Manager.

Thanks

http://pastebin.com/g54NZi0i

roberj13@gmail.com

**Comment by bcrook** [comment]
done

**Comment by ghost** [comment]
bcrook, 

Actually, I need to change the address of the manifest. It helps if it would have made it into a shared folder..

http://pastebin.com/aLxnUgZV

Thanks

**Comment by bcrook** [comment]
Okay. I updated it.

**Comment by bcrook** [comment]
I think your https://dl.dropbox.com/u/6734218/blueenergy.js is wrong.

Doesn't look like you close all the brackets properly at the end.

**Comment by ghost** [comment]
Yeah thanks, I just noticed as I received the email, will fix. Appreciate it.

**Comment by ghost** [comment]
Can you take a look at my file that you linked above. I changed it, I can't figure out why it is not working still.

Thanks

**Comment by bcrook** [comment]
Add a comma after line 16. it should like this:

```
   urls:
           [
            "http://dl.dropbox.com/u/6734218/Blue-Energy_ROM_600SV84.zip",
           ]
```

instead of
       urls:
               [
                "http://dl.dropbox.com/u/6734218/Blue-Energy_ROM_600SV84.zip"
               ]

**Comment by ghost** [comment]
It's still not working either way. I noticed Slayher's isn't working ATM either. I will have start again tomorrow, I can't think anymore.
