### ISSUE TITLE
Add to ROM Manager Manifest

### ISSUE THREAD

**Issue by lllboredlll** [koush/ROMManagerManifest#124]
ROM Manager manifest  http://htc-tweaker.com/IncROM/manifest.js

IncROM manifest http://htc-tweaker.com/IncROM/IncROM.js

thanks....

**Comment by pcmac77** [comment]
done

**Comment by lllboredlll** [comment]
Is it something I did that caused it to be in the premium section?

**Comment by pcmac77** [comment]
Because you didn't have "free: true".  I've added it for you.

**Comment by lllboredlll** [comment]
thank you sir

**Comment by lllboredlll** [comment]
i made a typo in the rom manager manifest... the url is htc-tweaker not htc-tweakers....are you able to fix this for me?
