### ISSUE TITLE
New entry for Rom Manager

### ISSUE THREAD

**Issue by slayher** [koush/ROMManagerManifest#13]
Looking to get my themed Roms on Rom Manager.
http://cyanogenmod.pastebin.com/wa1jcm90

There is the first java file, Let me know if I need to fix it.

Thanks
Tony.

**Comment by bcrook** [comment]
I commited it. Watch those trailing commas. ie. line 17:
}, should be }

Your personal manifest has the same problem.

**Comment by bcrook** [comment]
I fixed the trailing commas in the RM side manifest. More details on trailing commas:
http://github.com/koush/ROMManagerManifest/commit/4606e1662d1a6ee5da8b9ad0851c57f97cf5ee46

**Comment by slayher** [comment]
Ok thank you.  I just copy and pasted the example from koushs blog. I will take a look at it though.

**Comment by bcrook** [comment]
Also, make sure everything is all lined up and pretty. Helps you see errors and makes it easier for us

**Comment by slayher** [comment]
I will try.  I am not a programmer so I will do my best :)

**Comment by bcrook** [comment]
I know the feeling. Take out the comments too, unless you need them.

**Comment by slayher** [comment]
Ya it won't load for me atm, giving the error
org.json.JSONException: Expected a ',' or '}' at character 1904 of {
Trying to find character 1904

**Comment by bcrook** [comment]
Try this:
http://dl.dropbox.com/u/2992899/manifest_slayher_revised.js

**Comment by slayher** [comment]
Got it.  I had really close to what you sent.  The one you link was missing a comma, and my version was missing the comma you saw lol.

Thank you for the help
