### ISSUE TITLE
Dropbox FTL

### ISSUE THREAD

**Issue by slayher** [koush/ROMManagerManifest#14]
Sorry I need to update where the manifest will be.  Apparently dropbox did not like the amount of traffic I created.
Here is the new link. "http://www.android.antbox.org/slayher/manifest.js"

**Comment by bcrook** [comment]
Okay, changed it. Hopefully it will work now...

**Comment by slayher** [comment]
It was working earlier today but now the www on the url is breaking it.  I don't know why it changed, but could you take www out of the url
Thanks

**Comment by bcrook** [comment]
Done.
