### ISSUE TITLE
Please add my manifest to the master ROM Manager manifest

### ISSUE THREAD

**Issue by GFlam** [koush/ROMManagerManifest#144]
Hi could you please change the GFlam section to this I will no longer be doing themes because I have switched to developing. Me and Eagle1967 from droidforums have built a rom called Sourcery which will be released tomorrow but no hurry on the rom manager spot. Sorry about the switch but here is the link to the new manifest for Sourcery.

http://www.sourceryrom.com/ROMmanager/sourcery.js

Thank you again
GFlam

**Comment by koush** [comment]
done
