### ISSUE TITLE
help with OTA

### ISSUE THREAD

**Issue by nitr8** [koush/ROMManagerManifest#147]
koush, 

I am struggling to get OTA working

In my build.prop I have:
ro.modversion=Insanity-0.2.7
ro.rommanager.developerid=insanity

In my manifest (http://insanity.rollus.net/manifest.js) i have the following:
incremental: 0028,
modversion: "Insanity-0.2.8",

However OTA thinks there is no updates needed.  What am I missing?

Thanks for your help.

**Comment by koush** [comment]
You need to keep the old version "Insanity-0.2.7" in your manifest too. The updater looks at all your ROMs in the list to find the upgrade path.

If you dont want older versions to be listed, you can put a:
visible: "false"
in there.

**Comment by nitr8** [comment]
koush,

Thanks for that so take a butchers at this:

My current rom:
Has this
ro.modversion=Insanity-0.3.0
ro.rommanager.developerid=insanity

my manifest has this:
    {
        name: "Insanity-0.3.1",
        developer: true,
        summary: "ALPHA - Testing just for nitr8 (DO NOT USE)",
        device: "all",
        product: "Insanity",
        incremental: 0031,
        modversion: "Insanity-0.3.1",
        url: ""
    },
    {
        name: "Insanity-0.3.0",
        developer: true,
        summary: "ALPHA - Testing just for nitr8 (DO NOT USE)",
        device: "all",
        product: "Insanity",
        incremental: 0030,
        modversion: "Insanity-0.3.0",
        screenshots:
        [
        "http://insanity.rollus.net/screenshot/home-t.png",
        "http://insanity.rollus.net/screenshot/apps-t.png",
        "http://insanity.rollus.net/screenshot/lock-t.png"
        ],
        urls:
        [
    //"http://insanity.xxxxxx.net/rom/XXJPY-Insanity-0.28.zip",
    "http://insanity.rollus.net/rom/XXJPY-Insanity-0.28.zip"
        ],
        addons:
        [
        {
            name: "Samsung Keyboard",
            urls:
            [
            "http://insanity.rollus.net/addons/AxT9IME.zip"
            ]
        },
        {
            name: "Megga Sound Pack",
            urls:
            [
            "http://insanity.rollus.net/addons/SoundPack.zip"
            ]
        }
        ]
    }

But still no update available ? anything i can do to trace?

logcat dont give me much understandable 
V/InputDevice( 3113): ID[0]=0(0) Dn(0=>1)
V/WindowManager( 3113): Dsptch > Window{48c12728 com.koushikdutta.rommanager/com.koushikdutta.rommanager.RomManager paused=false}
V/WindowManager( 3113): Dsptch > Window{48c12728 com.koushikdutta.rommanager/com.koushikdutta.rommanager.RomManager paused=false}
V/InputDevice( 3113): ID[0]=0(0) Up(1=>0)
E/MediaPlayer( 3113): Unable to to create media player
W/AudioService( 3113): MediaPlayer IOException: java.io.IOException: setDataSource failed.: status=0x80000000
I/ROMManager( 3925): Downloading: http://gh-pages.clockworkmod.com/ROMManagerManifest/manifests.js
I/RomNexus( 3925): Using gzip for download.
D/dalvikvm( 3925): GC_FOR_MALLOC freed 4082 objects / 635416 bytes in 57ms
E/DownloadService( 3925): No value for id
E/DownloadService( 3925): org.json.JSONException: No value for id
E/DownloadService( 3925):   at org.json.JSONObject.get(JSONObject.java:354)
E/DownloadService( 3925):   at org.json.JSONObject.getString(JSONObject.java:510)
E/DownloadService( 3925):   at com.koushikdutta.rommanager.DownloadService$3.run(DownloadService.java:325)
I/ROMManager( 3925): Downloading: http://insanity.rollus.net/manifest.js
I/ActivityManager( 3113): Starting activity: Intent { flg=0x14000000 cmp=com.koushikdutta.rommanager/.RomManager (has extras) }
D/PersistentEventStore/putEvent( 3925): Row ID: 74, Event ID: 74
D/dalvikvm( 3925): GC_FOR_MALLOC freed 10434 objects / 689288 bytes in 32ms
D/NetworkRequestUtil/ConstructEventRequestPath( 3925): /__utm.gif?utmwv=4.5ma&utmn=1851606696&utmt=event&utme=5(Device_galaxys_Premium)(0)&utmcs=UTF-8&utmsr=480x800&utmul=en-US&utmac=UA-4956323-3&utmcc=__utma%3D999.235877501.1293904408.1293914453.1293914574.25
I/ROMManager( 3925): Downloading: http://rommanager.appspot.com/manifests/devices.js
D/PersistentEventStore/putEvent( 3925): Row ID: 75, Event ID: 75
D/PersistentEventStore/putEvent( 3925): Row ID: 76, Event ID: 76
D/PersistentEventStore/putEvent( 3925): Row ID: 77, Event ID: 77
I/SuperPowerSvc( 3422): [SuperPowerSvc] App launched: [com.koushikdutta.rommanager]
D/PersistentEventStore/putEvent( 3925): Row ID: 78, Event ID: 78
D/NetworkRequestUtil/ConstructEventRequestPath( 3925): /__utm.gif?utmwv=4.5ma&utmn=1845416522&utmt=event&utme=5(ROM_Insanity-0.3.0_Premium)(0)&utmcs=UTF-8&utmsr=480x800&utmul=en-US&utmac=UA-4956323-3&utmcc=__utma%3D999.235877501.1293904408.1293914453.1293914574.25
D/NetworkRequestUtil/ConstructEventRequestPath( 3925): /__utm.gif?utmwv=4.5ma&utmn=1853243019&utmt=event&utme=5(ROMDeveloper_insanity_Premium)(0)&utmcs=UTF-8&utmsr=480x800&utmul=en-US&utmac=UA-4956323-3&utmcc=__utma%3D999.235877501.1293904408.1293914453.1293914574.25
D/NetworkRequestUtil/ConstructEventRequestPath( 3925): /__utm.gif?utmwv=4.5ma&utmn=1391859068&utmt=event&utme=5(Developer_insanity_Insanity-0.3.0)(0)&utmcs=UTF-8&utmsr=480x800&utmul=en-US&utmac=UA-4956323-3&utmcc=__utma%3D999.235877501.1293904408.1293914453.1293914574.25
D/NetworkRequestUtil/ConstructPageviewRequestPath( 3925): /__utm.gif?utmwv=4.5ma&utmn=1591827322&utmcs=UTF-8&utmsr=480x800&utmul=en-US&utmp=%2FROM_Manager&utmac=UA-4956323-3&utmcc=__utma%3D999.235877501.1293904408.1293914574.1293914585.26
I/RomNexus( 3925): Safe Device ID: A4F403B911F759794687F953CFFFE522
I/RomNexus( 3925): onCreate finished
I/ActivityManager( 3113): Displayed activity com.koushikdutta.rommanager/.RomManager: 385 ms (total 385 ms)
I/RomNexus( 3925): Using gzip for download.
D/dalvikvm( 3925): GC_FOR_MALLOC freed 3642 objects / 192616 bytes in 37ms
W/PowerManagerService( 3113): Timer 0x3->0x3|0x0

**Comment by koush** [comment]
irc.freenode.net #koush, let's debug this

**Comment by koush** [comment]
I do not see anything immediately wrong. can you send me your current rom's build.prop?

**Comment by nitr8** [comment]
thanks, on irc now will lirc there for a while :p

I cannot seem to be able to attached anything, so here is a cut and past of build.prop.

ro.build.id=FROYO
ro.build.display.id=Insanity-0.3.0
ro.modversion=Insanity-0.3.0
ro.build.version.incremental=XXJPY
ro.build.version.sdk=8
ro.build.version.codename=REL
ro.build.version.release=2.2.1
ro.build.date=01.01.2011 - 17:00:00 GMT
ro.build.date.utc=1292826957
ro.build.type=user
ro.build.user=root
ro.build.host=nfye
ro.build.tags=release-keys
ro.product.model=GT-I9000
ro.product.brand=samsung
ro.product.name=GT-I9000
ro.product.device=GT-I9000
ro.product.board=GT-I9000
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.manufacturer=samsung
ro.product.locale.language=en
ro.product.locale.region=GB
ro.wifi.channels=
ro.rommanager.developerid=insanity
ro.board.platform=s5pc110
ro.build.product=GT-I9000
ro.build.description=GT-I9000-user 2.2.1 FROYO XXJPY release-keys
ro.build.fingerprint=samsung/GT-I9000/GT-I9000/GT-I9000:2.2/FROYO/XXJPO:user/release-keys

# SAMSUNG PROPERTIES

ro.build.PDA=I9000XXJPY
ro.build.hidden_ver=I9000XXJPY
ro.build.changelist=757011
ro.tether.denied=false

# SYSTEM PROPERTIES FOR SMDKC110

rild.libpath=/system/lib/libsec-ril.so
rild.libargs=-d /dev/ttyS0
ro.sf.lcd_density=240
dalvik.vm.heapsize=48m
dalvik.vm.execution-mode=int:jit
ro.opengles.version=131072

# ADDITIONAL BUILD PROPERTIES

windowsmgr.max_events_per_sec=55
keyinputqueue.use_finger_id=true
media.stagefright.enable-player=true
media.stagefright.enable-meta=true
media.stagefright.enable-scan=true
media.stagefright.enable-http=true
keyguard.no_require_sim=true
ro.config.ringtone=Terminated.ogg
ro.config.notification_sound=Haze.ogg
ro.config.alarm_alert=Morning.ogg
ro.opengles.version=131072
net.bt.name=Android
dalvik.vm.stack-trace-file=/mnt/sdcard/insanity/log/stacktrace.txt

**Comment by nitr8** [comment]
whooops, closed by mistake :) but still an issue for me :p
