### ISSUE TITLE
Flash alternative recovery and updated CWM-recovery for HTC Desire (bravo)

### ISSUE THREAD

**Issue by shawe** [koush/ROMManagerManifest#149]
I see on:

https://github.com/koush/ROMManagerManifest/blob/gh-pages/devices.js
https://github.com/koush/ROMManagerManifest/blob/gh-pages/devices2.js

That HTC Desire (bravo) don't have support for flash an alternative recovery, but people with S-OFF can flash it without problems.
I suppose that is a hard work to you have all devices updated, for this reason I'm giving to you a little help for update the HTC Desire device ;)

Here you have a RA-desire-v2.0.0 [GSM]:
http://forum.xda-developers.com/showthread.php?t=839621
With direct link: http://files.androidspin.com/downloads.php?dir=amon_ra/RECOVERY/&file=recovery-RA-desire-v2.0.0.img
Here you have RA-desire-v2.0.1 [GSM]:
With direct link: http://www.wuala.com/HTC_Desire/Recovery/AmonRA/recovery-RA-desire-v2.0.1.img

Here you have ClockworkMod Recovery v2.5.1.8:
http://forum.xda-developers.com/showthread.php?t=839640
Update ZIP format: http://www.multiupload.com/JB1B50GTU0
Update ZIP format with direct link: http://www.wuala.com/HTC_Desire/Recovery/ClockWorkMod/recovery-clockwork-2.5.1.8-bravo.zip
Flashable format: http://www.multiupload.com/TJADIV6UD7
Flashable format with direct link: http://www.wuala.com/HTC_Desire/Recovery/ClockWorkMod/recovery-clockwork-2.5.1.8-bravo.img

Here you have ClockworkMod Recovery v2.5.1.8 translated by me to Spanish:
Update ZIP format with direct link: http://www.wuala.com/HTC_Desire/Recovery/ClockWorkMod/ClockWorkMod%20Recovery%20v.2.5.1.8%20Bravo%20en%20Español/update_ClockWorkMod_Recovery_v.2.5.1.8_bravo-es.zip
Flashable format with direct link: http://www.wuala.com/HTC_Desire/Recovery/ClockWorkMod/ClockWorkMod%20Recovery%20v.2.5.1.8%20Bravo%20en%20Español/ClockWorkMod_Recovery_v.2.5.1.8_bravo-es.img

Thanks for your hard work koush :)

**Comment by koush** [comment]
Shawe, those links are not used anymore by ROM Manager. Instead, I use:
http://rommanager.appspot.com/manifests/devices.js

Do you still need me to list these recoveries?
