### ISSUE TITLE
Extras Manifest

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#150]
Hi Koush,

Please could you add this to your manifest : http://www.nfye.com/insanity-extras.js 

Best regard's RolluS ;)

**Comment by pcmac77** [comment]
RolluS,
Shouldn't the extras be under your manifest's optional "addons" section?  Just wondering...

Peter

**Comment by nitr8** [comment]
pcmac77,

Insanity ROM is managed by me, it is a minimalistic rom and I do not handle the addons thems and so-forth. The idea was also to let RolluS and trojan handle that for us as well as have them in the free manifest so any insanity user can use it, unlike the premium that insanity rom is in. I do not also wanna give access to the other people to the insanity server / manifest :)

Thanks a mill.

P.S. is there any info on the limitations between "free" & "premium" manifests? I could not find any info on this subject.

**Comment by pcmac77** [comment]
done.  sorry for the delay.
