### ISSUE TITLE
MD5SUM check for downloaded .img and .zip files

### ISSUE THREAD

**Issue by tjaderxyz** [koush/ROMManagerManifest#16]
Currently ROM Manager flashes downloaded .img files without checking for integrity. It should at least check the MD5SUM of the downloaded file to prevent flashing a corrupt recovery.
It would also be nice if it checked MD5SUMs of .zip files before rebooting into recovery to flash them, so that the user doesn't have to wait until the recovery complains about the signature to realiaze the .zip is corrupt.

**Comment by n-i-x** [comment]
excellent idea!

**Comment by fearphage** [comment]
This actually goes a bit deeper and is partially related to the fact that ROM Manager doesn't even [check for the existence of files before it reboots](https://github.com/koush/ROMManagerManifest/issues/issue/115).

**Comment by droidzone** [comment]
It shouldnt be hard to add a md5sum function to Rom Manager and should be considered

**Comment by bttnns** [comment]
This shouldn't be much of an issue because the file should be downloaded using a TCP connection, ensuring reliable data transfer.  But it would not be that difficult to add for increased verification on your downloads.
