### ISSUE TITLE
Request addition of ROM manifest to ROM Manager

### ISSUE THREAD

**Issue by droidzone** [koush/ROMManagerManifest#160]
{
    // This is what name you want your ROMs to show up under.
    developer: "Droidzone",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
    id: "droidzone",
    // The display summary. Two lines max.
    summary: "Sense ROM for HTC Desire with Stable Data2SD",
    // The location of the developer's manifest.
    manifest: "http://www.eyrie.in/Android/ROMS/ROM_Manager/manifest.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
    roms:
    {
        bravo: true,
    }
}

**Comment by droidzone** [comment]
Maybe I should have given the manifest as a file..
Here it is..Could you please add my ROM StarBurst?

http://www.eyrie.in/Android/ROMS/ROM_Manager/sent.js

**Comment by tp4bama** [comment]
Hey im the new miui porter for the D1 can you add me to rom manager. Here is my manifest: http://yeagsmedia.com/android/tp4bama/RomManagerManifest/tp4bama.js

**Comment by koush** [comment]
done
