### ISSUE TITLE
ROM still has not been added to Manifest

### ISSUE THREAD

**Issue by droidzone** [koush/ROMManagerManifest#163]
I've opened an issue previously for addition of my ROM StarBurst to the Manifest. Is there an eligibility criteria to satisfy? I havent seen even a comment about my manifest. Kindly add the ROM to the manifest soon.

http://www.eyrie.in/Android/ROMS/ROM_Manager/sent.js

**Comment by pcmac77** [comment]
done

**Comment by droidzone** [comment]
Thank you!
