### ISSUE TITLE
MIUI for HTC Vision

### ISSUE THREAD

**Issue by auma** [koush/ROMManagerManifest#165]
Hi,

could you please add my MIUI port for HTC Vision to ROM Manager?
http://web15.public1.linz.at/files/developer.js

Thank you!
g4rb4g3

{
    // This is what name you want your ROMs to show up under.
    developer: "MIUI",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
    id: "g4rb4g3",
    // The display summary. Two lines max.
    summary: "MIUI port for HTC Vision",
    // The location of the developer's manifest.
        manifest: "http://web15.public1.linz.at/files/miui-vision.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
    roms:
    {
        vision: true,
    }
}

**Comment by koush** [comment]
done

**Comment by auma** [comment]
Thanks, but is it normal that it is listed under premium?
Virtuous Rom is in the free category, I would like to have my Rom there too.

**Comment by auma** [comment]
ok, its under free now.

Thank you!
