### ISSUE TITLE
Rom to be listed on Rom manager

### ISSUE THREAD

**Issue by siulmagic** [koush/ROMManagerManifest#167]
heres the js file http://www.mediafire.com/?36b465060x32li0

regards luis

**Comment by HCDRJacob** [comment]
Do it properly

**Comment by siulmagic** [comment]
its is properly, whats wrong with it?

**Comment by HCDRJacob** [comment]
Not the script. Aren't you meant to fork the repo and add it yourself? I may be completely wrong and making a fool of myself, in which case sorry.

**Comment by siulmagic** [comment]
here my manifest file http://www.mediafire.com/?tmis2etg8wlvn5c

**Comment by siulmagic** [comment]
can anyone one please ad the manifest file, thats all thats left for my rom to be in rom manager list

**Comment by pcmac77** [comment]
Siulmagic, HCDRJacob was right, that the best way to go about adding a rom is to fork, add your changes, then send a pull request.  With that said, I did take a quick look at both your developer manifest and rom manifest, and both contain some fatal errors.  If you had created a pull request, we could at least take a look at your code and make inline comments.  In any case, please familiarize yourself a bit more with git and GitHub, and thank you for wanting to contribute.  Let me know if you have further questions.

**Comment by Mrbobrowitz** [comment]
your manifest file cannot be a mediafire download link, you have to host it somewhere. I will add you in once that is the case.

**Comment by siulmagic** [comment]
is this ok? http://theunholy.site88.net/siulmagic_manifest.js
