### ISSUE TITLE
Rom Manager

### ISSUE THREAD

**Issue by jdlfg** [koush/ROMManagerManifest#17]
Koush here is my info and would like to add my kernels to rom manager. 2.6 .29 eclair.

**Comment by koush** [comment]
You don't have a valid manifest url:
git://github.com/jdlfg/jdlfg.js.git
That's not a actual url that I can access via http...

**Comment by jdlfg** [comment]
Ok I will take care of this..

**Comment by jdlfg** [comment]
Im assuming you prefer not to use a dropbox url?

**Comment by koush** [comment]
Dropbox may work, so long as you dont go over your bandwidth limit.

**Comment by bcrook** [comment]
Is this done?

**Comment by koush** [comment]
Yup
