### ISSUE TITLE
New Manifest - Rom:NSCollab Device:Crespo

### ISSUE THREAD

**Issue by frank707** [koush/ROMManagerManifest#177]
{
    developer: "NSCollab",
    id: "frank707",
    summary: "A best of both worlds rom for your Nexus S",
    manifest: "http://studiousmedia.com/crespo/nscollab.js",
    roms:
    {
        crespo: true,
    }  
}

**Comment by pcmac77** [comment]
adding, but please check for syntax error in your rom manifest: http://studiousmedia.com/crespo/nscollab.js

**Comment by frank707** [comment]
updated the rom manifest.

http://studiousmedia.com/crespo/nscollab.js

could you shorten summary down to just :

summary: "A best of both worlds rom for your Nexus S",

**Comment by koush** [comment]
This taken care of?

**Comment by frank707** [comment]
Doesn't seem to be showing up on rom manager.

**Comment by pcmac77** [comment]
soon

**Comment by koush** [comment]
Maybe pcmac77 forgot to push. I'll add this myself.

**Comment by koush** [comment]
Ok, it's added, and your manfiest seems to work.

**Comment by pcmac77** [comment]
thx, koush

**Comment by frank707** [comment]
Appreciate it, thank you
