### ISSUE TITLE
Updating Developer ID In RM

### ISSUE THREAD

**Issue by JsinLegacy** [koush/ROMManagerManifest#18]
I moved to a new server and need my info updated if its not to much trouble...here is the newest id info

{
       developer: "JsinLegacy",
       id: "JsinLegacy",
       summary: "Custom Themes & Goodies",
       manifest: "http://www.jbthemes.com/Flavored_Ice/jairomeo.js",
       roms:
       {
            sholes: true,
        passion: true  
       },
}

**Comment by bcrook** [comment]
No trouble. In the file here: http://www.jbthemes.com/Flavored_Ice/jairomeo.js
The 3rd last line has a trailing comma, can you remove it please?
It breaks in Froyo.

**Comment by JsinLegacy** [comment]
okay I think I got it ...good thing there was something wrong I put the wrong link in.. anyways let me know if there are any other issues

{
       developer: "JsinLegacy",
       id: "JsinLegacy",
       summary: "Custom Themes & Goodies",
       manifest: "http://www.jbthemes.com/jsinlegacy/jsinlegacy.js"
       roms:
       {
            sholes: true,
        passion: true  
       },
}

**Comment by bcrook** [comment]
Im confused. Which is the correct link?

**Comment by JsinLegacy** [comment]
yeah sorry I when I was copying and pasting some things I put the wrong one in... the link in the revision is the correct one.. the one listed with "jsinlegacy" ... sorry for the confusion

**Comment by bcrook** [comment]
that link (http://www.jbthemes.com/jsinlegacy/jsinlegacy.js) is broken

**Comment by JsinLegacy** [comment]
ok link should be functional now... was adding some things to the jsinlegacy.js  its up and running now

**Comment by bcrook** [comment]
Okay, test it and let me know. If all is good I will close it. Sorry if I was rushing your work lol.

**Comment by JsinLegacy** [comment]
You're fine... yeah the link is functional... everything should be good to go

**Comment by bcrook** [comment]
Okay. Hope this is it.
