### ISSUE TITLE
New js file for ROM Manager

### ISSUE THREAD

**Issue by martinlong1978** [koush/ROMManagerManifest#19]
{
    // This is what name you want your ROMs to show up under.
    developer: "MartinLong",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
    id: "martinlong1978",
    // The display summary. Two lines max.
    summary: "Froyo roms for Desire",
    // The location of the developer's manifest.
    manifest: "http://www.rozel.net/martin/manifest.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
    roms:
    {
        bravo: true
    }
}

**Comment by martinlong1978** [comment]
http://pastebin.com/f7rEniRc

**Comment by koush** [comment]
Thanks martin, looks good! However, I noticed a problem in your ROM list, invalid JSON:

```
    ],
},
]
```

}

You have trailing commas with no further items.

**Comment by martinlong1978** [comment]
ok I've fixed it now... although I'm sure I saw this in your examples. I thought it was strange at the time.

**Comment by koush** [comment]
Yeah, I fixed up my example :)

**Comment by martinlong1978** [comment]
I have to say your recovery is a breath of fresh air!

Do you cache roms or something...? they download much quicker than I normally get from rapidshare!

Nice product.

**Comment by koush** [comment]
Yes, ROMs are cached on the SD card, so if you already have it, it won't DL it again.
