### ISSUE TITLE
Wrong alternate recovery for Supersonic

### ISSUE THREAD

**Issue by DrMacinyasha** [koush/ROMManagerManifest#192]
ROM Manager lists the alternate recovery for Supersonic as "RA Recovery v2.2.2". Amon_RA Recovery 2.2.2 has never existed, and the file it downloads usually ends up (in my experience) being corrupt, resulting in an unusable recovery.

The latest version for Supersonic is v2.3, and I have all of the current versions for all supported devices mirrored on goo-inside.me:
http://goo-inside.me/amon_ra/

**Comment by koush** [comment]
i'm gonna move back to a devices.js on github soon. I'll fix this.

**Comment by DrMacinyasha** [comment]
fscking FIXED. My OCD can now rest for five minutes.

**Comment by koush** [comment]
i'll need to release a new version of RM first

**Comment by DrMacinyasha** [comment]
Meh, at least when you do, it'll be updated.
