### ISSUE TITLE
Ultimate Droid Manifest

### ISSUE THREAD

**Issue by blackdroid** [koush/ROMManagerManifest#2]
{
    developer: "Ultimate Droid",
    id: "blackdroid",
    summary: "As many features as you can possibly get without sacrificing stabiltiy",
    manifest: "http://www.regalgs.org/droid/udmanifest.js",
    roms:
    {
        sholes: true
    },
}

**Comment by koush** [comment]
Hrm, can you try a pastebin instead? Github is being lame and reformatting.. Or if you are comfortable with git, just fork my stuff, and send me a pull request.

I'll add what I can decipher right now.

**Comment by koush** [comment]
I have added you. But your URL http://www.regalgs.org/droid/udmanifest.js is broken at the moment.

**Comment by blackdroid** [comment]
I added the javascript file back

**Comment by blackdroid** [comment]
i was testing it with your script

**Comment by koush** [comment]
Cool, looks like you've got this figured out. Good luck! 

I also edited your first comment to reflect what your manifest looks like. I stripped out the comments and also the unnecessary passion: true thing. If you don't support a device, you don't need to list it.
