### ISSUE TITLE
CWM recovery for leo

### ISSUE THREAD

**Issue by arif-ali** [koush/ROMManagerManifest#208]
Hi,

Now that we have ROMs for HD (leo), We would like to add the CWM recovery support for the HD2 (leo) we have them compiled already, we can provide 3.0.0.6, 3.0.2.4, and 3.0.2.5.

The URL for 3.0.2.5 is below

http;//arif.homelinux.com/recovery/recovery-clockwork-3.0.2.5-leo.img

Others will be available in the same format soon

regards,
Arif

**Comment by koush** [comment]
is there any way i can build this?

**Comment by arif-ali** [comment]
This is my process,
- the recovery.fstab, that we use, has the following at the end of the line.

/sd-ext     auto        /dev/block/mmcblk0p2    /dev/block/mmcblk0
- and the off mode charging patch from cedesmith

https://github.com/cedesmith/cLK/blob/master/patches/cwm_off_charge_v2.patch
- copy over my kernel, into device/htc/leo as zImage and kernel

you can download that from arif.homelinux.com/zImage

The rest I use the following method. 

cp ./vendor/cyanogen/products/cyanogen_leo.mk buildspec.mk

. build/envsetup.sh

lunch cyanogen_leo-eng

make -j2 recoveryimage

I can test this for you, once you have compiled it.

**Comment by koush** [comment]
is this all checked into CM then?

**Comment by arif-ali** [comment]
I use the default from repo sync from, 

git://github.com/CyanogenMod/android.git
using the gingerbread branch

and then apply the fixes mentioned in my previous post

**Comment by ghost** [comment]
hi koush,

arif & me = we :-) as he said: default repo sync, prepare build environment and "make recoveryimage" builds the clockworkmod recovery "as it should". absolutely no problem, with every kernel available for the hd2.
there are two versions: 
- one for "magldr" (cotullas bootloader, which uses yaffs2 boot partition and is non-android-standard bootloader) and
- one for cedesmiths cLK (which is native android bootloader; he used codeauroras little kernel loader; this recovery is "what we wish to have" @ rom manager).
  it's a precondition for new ported recoveries that the device should have an android native bootloader...? then magldr is out of race, i believe: but if it's possible to provide also a magldr version, we would be happy to supply you the necessary edits for recovery.fstab, too: the majority of the hd2 community is using magldr.

sry, for english: i'm german ;)

**Comment by cedesmith** [comment]
hi.
to make recovery i use ( from memory as i don't have the machine in front of me now):
. build/envsetup.sh
breakfast leo
cd bootable/recovery
git apply cwm_off_charge_v2.patch
cd ../..
make recoveryimage

when power cord is connected pone boots normally but with screen off. bootloader will pass cmdline indicating offcharge mode to kernel and recovery.
patch creates a thread to manage led state and waits on a loop for power key press and when that happens reboots the phone. in the key wait loops also turns off the keys back light as kernel will start it on any key press.
peaty straight forward if you ask me :)

recovery.fstab is usually edited to add sd-ext partition

magldr does not yet support booting into recovery based on the reboot reason passed from android so i guess that would be the main problem but i hope that will come too.

**Comment by koush** [comment]
can you make teh patch a standalone executable for the leo tree that gets built?  i can make it get run on boot of recovery.

**Comment by cedesmith** [comment]
that would not work because then recovery will try to display menu and everything as usual but since panel hardware off kernel will wait for it and become unresponsive.
recovery already includes the function to handle_chargemode (the one i patched) but implementation is wrong as relays on filesize of /proc/cmdline witch is 0 and not cmdline len as code assumes. even if it will be corrected all will do it will be reboot the phone to normal mode.

what is wrong with having it included in recovery ? i think is a correction to existing code and it should also work for other devices (desire hd uses recovery for offcharge ?)

if is a problem with batch building the images i could speak with charnsingh to include it on leo device ( probably should do it anyway).

**Comment by koush** [comment]
Can you try this commit in Leo too?
https://github.com/CyanogenMod/android_device_htc_mecha/commit/163d636278ef737d2131f1342a94208fcc3366eb

That's how offmode was properly implemented.

The old handle_chargemode code was dead code that I actually just forgot to remove.

**Comment by ghost** [comment]
w/o any other changes? 
- deleted bootable/recovery and htc/leo
- repo sync and compiled recovery; resulting img is ~ 600kb bigger in size than the one compiled with cedes patches
- added line from commit
- switched phone off, plugged charger in -> device turns on w. display off, LED amber; no reaction when pressing any key
- pulled charger out -> device switched off, LED off; pressing power button turned phone on

need to do a full charge until LED turns green? doing it atm.

**Comment by arif-ali** [comment]
OK, I have tested this commit, so offmode charging is working. (i.e. without cedesmith patch)

pressing any of the buttons turns on the lights of the buttons, but nothing happens (i.e. the phone does not turn on when the power putton is pressed), the lights of the buttons turn off, after ~10 seconds

Taking the cable out of the phone turns the LEDs off (i.e. the LED to do with charging). And then pressing the power button allows the phone to turn back on

I hope that helps
Arif

Edit:
Snap seader, looks like we got the same result

**Comment by ghost** [comment]
jep, but for me the hardwarekey-lights stays on (from the beginning of offcharging).

but that's absolutely insignificant :) it works, yes. "BOARD_USES_RECOVERY_CHARGEMODE := true" is doing it.

LED turns to green if fully charged :) and then pressing power button turns the device on.

**Comment by koush** [comment]
So, then everything is wokring with my suggested change? Should I release this?

**Comment by arif-ali** [comment]
yes release it, it's better than the one at the moment, wrt to offmode charging, that's on RM already.

But, we still have the problem where when the phone has the cable connected, and the phone is off. we are not able to turn the phone back on.

I am pretty sure we were able to that before.

**Comment by koush** [comment]
Ok, the new recovery, 3.0.2.5 is on ROM Manager. Please test.

**Comment by arif-ali** [comment]
ok, that's working.

apart from the same issue we have reported in our previous messages.
