### ISSUE TITLE
[REQ] Addition to Rom Manager

### ISSUE THREAD

**Issue by RvU** [koush/ROMManagerManifest#21]
{
    // This is what name you want your ROMs to show up under.
    developer: "RvU Team",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
    id: "rvu",
    // The display summary. Two lines max.
    summary: "Custom ROM for the HTC Evo 4G",
    // The location of the developer's manifest.
    manifest: "http://www.fleshdroid.com/RvU/manifest1.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
    roms:
    {
        supersonic: true
    }
}

**Comment by bcrook** [comment]
Done. Can you confirm it works?

**Comment by RvU** [comment]
error occurred while processing the ROM list!

something on my end maybe?

**Comment by bcrook** [comment]
Did it fail on the list of all of the ROMs available or fail on the listing of just your ROMs

**Comment by RvU** [comment]
just mine.

rom entry shows under premium, when selected above error is shown

http://fleshdroid.com/RvU/manifest1.js <--link to manifest

**Comment by koush** [comment]
```
},
// And here's another, older ROM!
```

You have a trailing comma!

**Comment by bcrook** [comment]
im just going through it. Are you using the froyo parsing now?

**Comment by RvU** [comment]
Gracias.  Js fail

**Comment by bcrook** [comment]
RvU, try this:

{
    version: 1,
    homepage: "http://forum.androidcentral.com/htc-evo-4g-roms-hacks/15869-rom-rvu-1-3-2-working-4g-sync-fixed-rom-manager-support-new-post.html",
    donate: "http://ww5.komen.org/Donate/DonateOnline.html",
    roms:
    [
    {
        name: "RvU",
        summary: "Stable",
        device: "supersonic",
        product: "RvU",
        incremental: 132,
        modversion: "RvU-1.3.2-Evo4G",
        urls:
        [
        "http://fleshdroid.com/RvU/signed-RvU-1.3.2.zip"
        ]

```
}
]
```

}

**Comment by RvU** [comment]
Not on purpose :)  JS skills at an all time low here.  Through trial and error it appears to be downloading, or at least hasn't given an error

**Comment by koush** [comment]
Well, the parser is built into Android, if someone accesses it from Froyo his ROM will fail to list, but from Eclair it works fine. Lame!

**Comment by bcrook** [comment]
Sounds like its working - I will close this issue now :)
