### ISSUE TITLE
Evo Rom Request to add to RomManager

### ISSUE THREAD

**Issue by SinisterTensai** [koush/ROMManagerManifest#211]
Here is the description file
http://sinister.tensailabs.com/Sinister_Rom/SRdescription.js

**Comment by DrMacinyasha** [comment]
Do you have a 128x128 icon?

**Comment by SinisterTensai** [comment]
At the moment no. But I can make one easily enough, May take sometime though; currently have no computer access.

**Comment by DrMacinyasha** [comment]
I've got the edit for manifests.js queued up, however your ROM manifest has a ton of incorrect syntax. Here is a fixed version:
https://gist.github.com/926695

When you've got a 128x128 icon.png and the fixed Romlist.js uploaded, reply and I'll push the update.

**Comment by SinisterTensai** [comment]
128x128 icon http://sinister.tensailabs.com/Sinister_Rom/SinisterIcon.png
Romlist http://sinister.tensailabs.com/Sinister_Rom/Romlist.js

**Comment by DrMacinyasha** [comment]
Added.
