### ISSUE TITLE
ShadowFrost Manifest

### ISSUE THREAD

**Issue by IEF** [koush/ROMManagerManifest#22]
ShadowFrost roms for Bravo :)

Mind adding me to ROM Manager?

http://www.shadowchild.nl/IEF.js

And yeah, that's also my github ID :)

**Comment by bcrook** [comment]
Should be done. Please confirm that it works :)

**Comment by IEF** [comment]
I've been added, but it seems i'm under 'Premium', is that right?

**Comment by bcrook** [comment]
No it should be free based on the manifest. I'm at work and font have the command to check the listing. Maybe koush can look at it.

**Comment by IEF** [comment]
it's under Free now, somehow. Good :)
