### ISSUE TITLE
Adding Lightning Rom to Rom Manager

### ISSUE THREAD

**Issue by DhE17roms** [koush/ROMManagerManifest#223]
Koush,

Here's the description/developer javascript file. let me know if you need anything else.

https://github.com/downloads/DhE17roms/Roms/developer.js

Thanks,
-Dhemke17

**Comment by DrMacinyasha** [comment]
I'd recommend hosting your actual manifest using gh-pages rather than as a download/attachment.

**Comment by koush** [comment]
This ought to be fine so long as the download name does not change. But it would still be a pain in the ass for him to manage it.

**Comment by DhE17roms** [comment]
Im not 100% sure how to do this. Can you send me a link to read up on how to do this. It would be greatly appreciated

**Comment by DrMacinyasha** [comment]
http://pages.github.com/

Basically, create a repo and create the branch "gh-pages" on it, and place your manifest.js file in that branch. You'll then be able to access it at http://your_username.github.com/repo_name/manifest.js

**Comment by DhE17roms** [comment]
Got the pages set up and am working on getting the manifest there now. I will post up a new link as soon as its good to go. Thanks for the advise. I would like this to be as painless as possible.

**Comment by DhE17roms** [comment]
Got it all set up...let me know if this is all you need

Link to updated developer.js: https://github.com/downloads/DhE17roms/Roms/developer.js

Link to manifest file: http://dhe17roms.github.com/Roms/lightningrom.js

-Let me know if I need to do anything else.

**Comment by DrMacinyasha** [comment]
Just two things that I see in your manifest:

1) You use "roms" but only have one ROM listed. I'm not 100% sure, but I do think that might prevent any ROMs from showing up in the listing. If you have an older version ROM that you can list in there as well, or a spaceholder for an upcoming ROM, that should prevent any issues.

2) You can use gh-pages for hosting your ROM as well, you don't need to make it a download as well. Though honestly, hosting a ROM on github is more or less frowned upon. If you'd like some real hosting, message me. I've got plenty of space and bandwidth available on goo-inside.me.

**Comment by koush** [comment]
You can have one ROM listed fine

**Comment by koush** [comment]
And yes, I'd definitely be wary about hosting that large of a download on github. Go for it though, maybe they won't notice :P

**Comment by DrMacinyasha** [comment]
Merged.
