### ISSUE TITLE
Please add my Rom to RomManager

### ISSUE THREAD

**Issue by baadnewz** [koush/ROMManagerManifest#228]
{
    "developer": "Baadnewz",
    "free": "true",
    "id": "baadnewz",
    "icon": "http://insertcoin.dataninja.net/rommanager/logo.png",
    "manifest": "http://insertcoin.dataninja.net/rommanager/manifest.js",
    "roms": {
        "bravo": "true"
    },
    "summary": "Finest ports ever!"
},

**Comment by pcmac77** [comment]
and this replaces the old one?

**Comment by baadnewz** [comment]
yes, since i froyo development is discontinued, and i also lost u/p from that ftp and cant get in touch with the server owner.
Thanks and sorry for bothering

**Comment by DrMacinyasha** [comment]
Merged.
