### ISSUE TITLE
DeFroST 

### ISSUE THREAD

**Issue by richardtrip** [koush/ROMManagerManifest#23]
Do you want to add me to the Rom-Manager?

http://www.pctrip.nl/DeFroST/defrost.js

**Comment by bcrook** [comment]
You have a trailing comma and an extra curly brace at the end too, it should look like this:
    {
        version: 1,
        homepage: "",
        donate: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=support%40pctrip%2enl&lc=NL&item_name=Richard%20Trip&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted",
        roms:
        [
        {
            name: "DeFroST 0.9c",
            summary: "Stable",
            device: "bravo",
            product: "DeFroST",
            incremental: 0093,
            modversion: "DeFroST-0.9c",
            urls:
            [
            "http://b42.nl/richardtrip/DeFroST_0.9c_uvonly.zip"
            ],
            addons:
            [
            {
                name: "Kernel update UVOC 1267MHz+echomod",
                urls:
                [
                "http://b42.nl/richardtrip/DeFroST_0.9b_uvoc1267_noecho.zip"
                ]
            },
            {
                name: "Kernel update UVOC 1113MHz+echomod",
                urls:
                [
                "http://b42.nl/richardtrip/DeFroST_0.9b_uvoc1113_noecho.zip"
                ]
            }
            ]
        }
        ]
    }

**Comment by richardtrip** [comment]
I corrected the problem.

**Comment by bcrook** [comment]
Thanks!

**Comment by richardtrip** [comment]
Thank you.
