### ISSUE TITLE
Please add this to ROM Manager

### ISSUE THREAD

**Issue by stefansaraev** [koush/ROMManagerManifest#232]
here is the manifest:

--- cut ---
{ 
    "developer": "seo", 
    "free": "true", 
    "id": "seo", 
    "icon": "http://android.saraev.ca/download/rommanager/icon.png", 
    "manifest": "http://android.saraev.ca/download/rommanager/manifest.js", 
    "roms": { 
        "ace": "true" 
    }, 
    "summary": "ROMs for your HTC Desire HD" 
} 
--- cut ---

Thanks in advance
Stefan.

**Comment by DrMacinyasha** [comment]
1) Please add ROMs to your manifest and rename it to a .js
2) Please change your icon to a 128x128 png that's yours

And also, why "seo"? That's a tad... Generic. What's your ROM?

**Comment by pcmac77** [comment]
I was going to comment the same, but added the ROM anyway.
By the way, the ROM manifest has a dangling comma near the end.

**Comment by stefansaraev** [comment]
@DrMacinyasha : I just uploaded the first rom & filled the manifest. it is also available as .js now.
@pcmac77 : thank you very much.

**Comment by koush** [comment]
Can we rename this to something other than "seo"? His ROM is named TashakBate or something.

**Comment by stefansaraev** [comment]
well.. let it be "TB Roms". I will add some other roms soon (mt4g port, doubleshot and so on) and I don't realy care about the section name.

**Comment by pcmac77** [comment]
Renamed to "TB Roms"
