### ISSUE TITLE
delete rom from rom manager

### ISSUE THREAD

**Issue by baadnewz** [koush/ROMManagerManifest#233]
i don't wanna bother anyone too much, but in the moment i have 2 roms in rom manager. Insertcoin froyo - discontinued and Insertcoin Gingerbread Sense 2.1. For some reason OTA Update for IC GB don't work and i guess is because of the old one being there too 

So if it's not too much trouble can you please delete the info for insertcoin hd (froyo). I even don't have access to that ftp anymore.
Thanks

**Comment by Racle** [comment]
manifest 
"name": "Insercoin GingerBread CM7 V09",
"summary": "Stable",
"device": "bravo",
"product": "Insertcoin_cm7",
"incremental": "09",
"modversion": "InsertCoin_GB_Sense2.1_CM7_v09",
"url": "http://insertcoin.dataninja.net/Archive/InsertCoin_GB_Sense2.1_CM7_v09.zip"

and in rom there is 
ro.rommanager.developerid=baadnewz
ro.modversion=InsertCoin_GB_Sense2.1_CM7_v09

So setup should be okay. I think that tries to find manifest in old rom location, and don't find new rom info there when "Check for rom updates". Only shows "There is no update available for your ROM." even when manifest got v10 with incremental: "10"

EDIT: pulled commit change to manifest.js

**Comment by koush** [comment]
which one do you want me to remove?

**Comment by koush** [comment]
I see the two entries, let me know which one is outdated

**Comment by baadnewz** [comment]
this is the outdated one:
     {
            "developer": "baadnewz",
            "free": "true",
            "id": "baadnewz",
            "manifest": "http://baadnewz.lcdc.sk/rommanifest.js",
            "roms": {
                "bravo": "true" 
            },
            "summary": "DesireHD rom ported to desire.Stable and fast" 
        },

**Comment by koush** [comment]
Ok, I removed that one, thanks.
