### ISSUE TITLE
Shawe repo fro ROM Manager

### ISSUE THREAD

**Issue by shawe** [koush/ROMManagerManifest#24]
This is mine:

http://www.wuala.com/shawe_ewahs/Publica/Android/ROM%20Manager/shawe.js

Direct link for download:

http://content.wuala.com/contents/shawe_ewahs/Publica/Android/ROM%20Manager/shawe.js?lang=es

I require a Premium version of ROM Manager for add my "repo"?

**Comment by bcrook** [comment]
Okay its added. I need your IMEI to get you the premium version.  brian.w.crook@gmail.com

**Comment by bcrook** [comment]
Your manifest should be in there.

**Comment by shawe** [comment]
On github?

**Comment by bcrook** [comment]
You should see it under Premium in ROM Manager

**Comment by shawe** [comment]
Is not possible add my "repo" to free list?

**Comment by bcrook** [comment]
I can. You should've put a free: true line the manifest. I figured thats why you wanted premium access. Will change your manifest to free

**Comment by shawe** [comment]
Ok, I understand that for add my repo I must to have a Premium account. Sorry for my bad english :P

**Comment by bcrook** [comment]
That's fine. Your repo is now free and you have premium access. Enjoy :)

**Comment by shawe** [comment]
Thanks for the Premium :)
