### ISSUE TITLE
Update Lightning Rom manifest

### ISSUE THREAD

**Issue by DhE17roms** [koush/ROMManagerManifest#242]
I have added two themes for lightning rom as well as Vanilla Bean v1.0 and Vanilla Bean v1.1 which has screenshots.

here is my developer.js: https://github.com/downloads/DhE17roms/Roms/developer.js

{
        "developer": "dhemke17",
        "free": "true",
        "id": "DhE17roms",
        "icon": "https://github.com/DhE17roms/Roms/blob/gh-pages/auburn-university.jpg",
        "manifest": "http://dhe17roms.github.com/Roms/lightningrom.js",
        "roms": {
            "mecha": "true"
        },
        "summary": "Roms and Extras"
}

**Comment by DrMacinyasha** [comment]
Why are you opening an issue ticket? Your developer manifest (what is contained in this repo, under mainfests.js) has not changed. You don't need to open a ticket every time you edit your own manifest (the lightningrom.js). ROM Manager will automatically fetch the updated manifest, and show the changes.
