### ISSUE TITLE
Add my Rom, to ROM Manager please!

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#243]
{
    "developer": "DeltaProject",
    "free": "true",
    "id": "deltaproject",
    "icon": "http://deltarom.ru/roms/logo.png",
    "manifest": "http://deltarom.ru/roms/deltaprodesires.js",
    "roms": {
        "bravo": "true" 
    },
    "summary": "The best firmware on Android 2.3"
}

**Comment by DrMacinyasha** [comment]
I'm just going to warn you ahead of time, it is HIGHLY recommended that you add at least one other ROM to your manifest. Having one ROM, and using the "roms": field has been shown to cause issues in the past. You also need to add a product,  incremental, and modversion, fields if you want the ROM to be able to take advantage of all the capabilities of ROM Manager, such as ROM update notifications.

**Comment by koush** [comment]
1 rom should not matter..?

**Comment by DrMacinyasha** [comment]
I've troubleshooted with other developers who had only one ROM but used "roms", and ROM Manager threw errors when they tried to open their listing. It seems like it might be just as angsty about being plural as url/urls, screenshot/screenshots, and device/devices... Or they had some other formatting error that got in the way. I really need to take some time later and test this.

**Comment by koush** [comment]
"rom" is NOT supported. only "roms". even if there is only one. it is not handled in the same fashion as url/urls, screenshot/screenshots.

it was a formatting error probably.

**Comment by DrMacinyasha** [comment]
Ah. Alright. Still, this manifest really should get the product/incremental/product fields. @deltaproject, do you want me to merge in now, or wait until you add those?

**Comment by koush** [comment]
go ahead and merge now. i dont expect most people to add those things. they're optional.

**Comment by ghost** [comment]
So can update my manifest after adding new roms for other devices?

**Comment by DrMacinyasha** [comment]
Yes, that would be easily doable.
