### ISSUE TITLE
cyanogenmod nightlies for leo

### ISSUE THREAD

**Issue by arif-ali** [koush/ROMManagerManifest#245]
Can you add this in, which we are trying to maintain, thanks

```
{
  "developer": "CyanogenMod LEO Nightlies",
  "icon": "http://mirror.kanged.net/test/tdr.png",
  "id": "cyanogenmodleonightly",
  "manifest": "http://arif.homelinux.com/RM.js",
  "roms": {
    "leo": "true",
  },
  "summary": "CyanogenMod LEO Nightly builds. Very experimental and probably broken. Do not report bugs for these builds."
}
```

**Comment by rmcc** [comment]
Hm... no. The only things named "CyanogenMod" on RomManager come out of our buildbots. Not having those for LEO was a deliberate decision.

**Comment by arif-ali** [comment]
is there any other way we can add this, i.e. rename it to something else?

**Comment by koush** [comment]
yes, please call it a CM port or something so there is no confusion that it is not an official build.

**Comment by arif-ali** [comment]
Is this better, or do you want it to be renamed completely?

```
{
  "developer": "CM7 Nightlies",
  "icon": "http://mirror.kanged.net/test/tdr.png",
  "id": "cyanogenmodleonightly",
  "manifest": "http://arif.homelinux.com/RM.js",
  "free": "true",
  "roms": {
    "leo": "true",
  },
  "summary": "CM7 Nightly builds, unofficially built by charansingh, AirforcPrductions and arif-ali. Very experimental and probably broken. Do not report bugs for these builds."
}
```

**Comment by arif-ali** [comment]
I have updated the above comment, does that seem more reasonable?

**Comment by koush** [comment]
sure

**Comment by arif-ali** [comment]
ok, I would have presumed them to be free, and not premium, or are nightlies supposed to be premium?

**Comment by arif-ali** [comment]
ok, updated comment

**Comment by koush** [comment]
yes they're free

**Comment by arif-ali** [comment]
can we change the manifest to the following please

http://dl.dropbox.com/u/26430630/RM.js

thanks
