### ISSUE TITLE
Add my Rom, to ROM Manager please!

### ISSUE THREAD

**Issue by Spartach** [koush/ROMManagerManifest#247]
```
{
    "developer": "-=MDJ's ViVO Sense=-",
    "free": "true",
    "id": "spartach",
    "icon": "http://mdeejay.vpnonline.org/RomManagerManifest/logo.png",
    "manifest": "http://mdeejay.vpnonline.org/RomManagerManifest/mdeejaymod.js",
    "roms": {
        "ace": "true"
    },
    "summary": "Mods and bacon for DHD"
}
```

**Comment by koush** [comment]
done

**Comment by Spartach** [comment]
Sorry! You couldn`t change id?
Old version - "spartach"
New version - "mdj"
{
    "developer": "-=MDJ's ViVO Sense=-",
    "free": "true",
    "id": "mdj",
    "icon": "http://mdeejay.vpnonline.org/RomManagerManifest/logo.png",
    "manifest": "http://mdeejay.vpnonline.org/RomManagerManifest/mdeejaymod.js",
    "roms": {
        "ace": "true"
    },
    "summary": "Mods and bacon for DHD"
}
