### ISSUE TITLE
Rom install through rom manager app

### ISSUE THREAD

**Issue by rocafooh** [koush/ROMManagerManifest#257]
Installing the latest nscollab from rom manager seems to hang at the google bootscreen only when installing through rom manager w/ Wipe Dalvik enabled. The rom installs fine manually through recovery, and installs fine when wipe dalvik cache is de-selected in the installation options. Any idea why this may be?

**Comment by koush** [comment]
Try getting the latest ROM Manager. 4.3.1.3. I think this was fixed.

**Comment by DrMacinyasha** [comment]
Like koush said, it **should** be fixed in the latest version. If you're still having problems, try adding to the beginning of your updater-script to unmount /system, assuming you're just formatting /system first, then mounting it to copy over files.

**Comment by koush** [comment]
Yes, that will fix it for all users, regardless of what ROM Manager they are running.

**Comment by rocafooh** [comment]
Thanks for support. Works just fine now!
