### ISSUE TITLE
3.2.0.0 clockwork recovery initial assert fails when flashing VM670

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#265]
Issue Description:
LG Optimus V 3.2.0.0 Clockwork recovery fails at initial insert command when flashing a ROM.

reference post:
http://forum.xda-developers.com/showthread.php?p=14522363&highlight=build.prop#post14522363
/*
Originally Posted by bhelmore 
forum.androidcentral.com/optimus-v-rooting-roms-hacks/57485-how-root-lg-optimus-v.html

I downloaded the free version of ROM Manager and installed the CW recovery. After this point, things went south. No downloadable ROMs other than Extras and Google Apps appear in ROM Manager. Even after upgrading to the premium app, I still see no ROMs. I found a copy of the aospCMod-VM670-20110601-signed.zip elsewhere on this thread and tried installing the zip using ROM Manager and CW recovery. Neither work. The initial assert fails:

assert(getprop("ro.product.device") == "thunderc" || getprop("ro.build.product") == "thunderc" || getprop("ro.product.board") == "thunderc");

But my phone is an Optimus V and the getprop command from a terminal does show that ro.product.device is thunderc.
*/
fyi - the clockwork recovery 3.1.0.1 on the thread's first page does work
http://forum.xda-developers.com/showthread.php?t=962862

**Comment by koush** [comment]
I'll fix this, thanks.

**Comment by ghost** [comment]
any progress?

**Comment by ghost** [comment]
a lot of people became paying customers of ROM Manager once it was introduced in ROM Manager- myself included.  It'd be nice if we got something that worked.  As of right now the trash talk on the xda forums thread for ROM Manager are pretty bad.  If you could in the least slap the build from the link I attached in my 1st post this would be sufficient for now... (or fix your 3.2.0.0 version)

**Comment by koush** [comment]
#1 This is a recovery bug, not a ROM Manager bug. Recovery is open source; anyone is welcome to fix it. I appreciate your purchase, and realize that ROM Manager and Clockwork are tightly coupled. But CWR is intentionally open source so your community devs can help port it and fix issues.
#2 You can also simply remove the assert from the zip to fix this yourself.
#3 I'm just one guy essentially supporting 70+ phones. I fix bugs as quick as I can, in order of severity. I will get to this when I have a moment.

**Comment by koush** [comment]
This should now be fixed. Reflash your recovery.

**Comment by ghost** [comment]
Thanks koush. It worked
