### ISSUE TITLE
OTA Notifications not working from RM

### ISSUE THREAD

**Issue by ThunderStick** [koush/ROMManagerManifest#266]
I have been trying to find a problem with my OTA notifications not working, and I can't figure this out.  
These are my build.prop additions
ro.rommanager.developerid=ThunderStick
ro.modversion=TSGB1.2.0

and my manifest
http://www.igottadroid.com/Roms/RomManagerManifest/ThunderStick-RMM.js
This was working fine when using ROM Share but since I started hosting my own roms I cant for the life of me get and OTA Notifications.  
Also when clicking the Check For Rom Updates button nothing happens.
any help is appreciated...
Thanks in advance,
ThunderStick

**Comment by koush** [comment]
hide all your roms that are listed in rom share if you have not

**Comment by koush** [comment]
Btw, the it is "incremental" not "incrementals".

**Comment by ThunderStick** [comment]
Thanks again,
not sure how I missed that...
