### ISSUE TITLE
PirateRUM Manifest

### ISSUE THREAD

**Issue by boombuler** [koush/ROMManagerManifest#27]
Could you add

http://boombuler.de/ROMManager/piraterum.js

to the ROMManager?
Thx again for the great work!

**Comment by bcrook** [comment]
koush will this work? php?

**Comment by boombuler** [comment]
Sure... If you dont make a difference in your program. It is just a little php script that generates the json file from a mysql-db. So that I can write a little "ROMManager-Manager"-App when I have some time...

**Comment by koush** [comment]
Yep, it should work just fine!

**Comment by koush** [comment]
Nice idea! I started halfway down the path of a google app engine thing that does something pretty similar.

**Comment by boombuler** [comment]
I'll give you the source as soon as it is ready...

**Comment by bcrook** [comment]
Cool. I wasn't sure if it checked for a .js extension or anything.

**Comment by boombuler** [comment]
thx
