### ISSUE TITLE
Request: manifest url & summary change

### ISSUE THREAD

**Issue by romanbb** [koush/ROMManagerManifest#278]
developer: "Einherjar Dev Team"

manifest: http://romanbb.github.com/ROM-Manager-Manifest/manifest.js

devices: vibrant, vibrantmtd, g2x (p999?)

summary:  "ROMs, kernels, mods, and metal."

**Comment by koush** [comment]
you still need this?

**Comment by romanbb** [comment]
sent a pull request as you asked, no need for this anymore
