### ISSUE TITLE
Edit my repo info please

### ISSUE THREAD

**Issue by shawe** [koush/ROMManagerManifest#28]
Actually appears like this:

```
{
    developer: "Shawe",
    id: "shawe",
    summary: "ROM's para HTC Desire",
    manifest: "http://content.wuala.com/contents/shawe_ewahs/Publica/Android/ROM%20Manager/manifest.js?lang=es",
    free: true,
    roms:
    {
        bravo: true
    }
},
```

Can you edit it like this:

```
{
    developer: "Shawe",
    id: "shawe",
    summary: "ROM's for HTC Desire and extras",
    manifest: "http://content.wuala.com/contents/shawe_ewahs/Publica/Android/ROM%20Manager/manifest.js",
    free: true,
    roms:
    {
        bravo: true
    }
},
```

**Comment by bcrook** [comment]
Should be fixed.

**Comment by shawe** [comment]
You are update my manifest link but not the summary description, now people are saying me that it show an error, it could be fixed deleting "/sdcard/clockworkmod/download/content.wuala.com/contents/shawe_ewahs" on my case and access again to the repo for re-download de manifest again, probably this can be fixed on ROM Manager "forcing" re-download the manifest files.

**Comment by bcrook** [comment]
Sorry, I was being lazy. I did it properly now. 

I know T-Mo caches a lot so could be where the issue comes from. You can try it on Wifi to get past that.
