### ISSUE TITLE
Please add this ROM to RomManager

### ISSUE THREAD

**Issue by LoveBootCaptain** [koush/ROMManagerManifest#289]
Hey,

i wanted to please you to add this ROM to RomManager Support.

You find my Sources here:

https://github.com/LoveBootCaptain/Saga-LBC-Mod-OTA/blob/master/manifest

source of manifest.js file ist here:

https://github.com/LoveBootCaptain/Saga-LBC-Mod-OTA/blob/master/manifest.js

if you need more informations please contact me.

sadly i´m new into github and can´t make it another way... sorry for any trouble and thanks for your great possibilities.

regards

stephan

**Comment by DrMacinyasha** [comment]
Please use http://romshare.deployfu.com

It supports manual manifests.
