### ISSUE TITLE
CrunchySoft ROM Manifest

### ISSUE THREAD

**Issue by crunchysoft** [koush/ROMManagerManifest#29]
Here is my js:

```
{
    developer: "crunchybutternut",
    id: "crunchybutternut",
    summary: "Fast and fully themed ROMs for the CDMA Hero.",
    manifest: "http://crunchysoft.pocketdevelopers.com/ROMManagerManifest/crunchysoft.js",
    roms:
    {
        heroc: true,
        free: true,
    }
}
```

Alternate:
http://pastebin.com/EP5RaBn8

**Comment by bcrook** [comment]
Can you test, please?

**Comment by bcrook** [comment]
Its not letting me add from here. Stupid github/bcrook. 

Sorry, I will try when I am home.

**Comment by bcrook** [comment]
Okay, so I added it but you have errors in the file. You need to remove ALL trailing commas. The last entry in every section doesn't have a comma. For example, 

```
    addons:
    [
    {
        name: "FCFix",
        urls:
        [
        "http://crunchysoft.pocketdevelopers.com/misc/patch/2.0.1-FC-Fixes.zip",
        ]
    },
```

needs to change to

```
    addons:
    [
    {
        name: "FCFix" //comma removed
        urls:
        [
        "http://crunchysoft.pocketdevelopers.com/misc/patch/2.0.1-FC-Fixes.zip" //comma removed
        ]
    },
```

**Comment by crunchysoft** [comment]
So even the beginning needs to have the commas removed?
before:
        name: "Buufed 2.0.1",
        summary: "Stable",
        device: "heroc",
        product: "Buufed",
        incremental: 201,
        modversion: "Buufed-2.0.1",
        screenshots:
After:

```
    name: "Buufed 2.0.1"
    summary: "Stable"
    device: "heroc"
    product: "Buufed"
    incremental: 201
    modversion: "Buufed-2.0.1"
```

**Comment by bcrook** [comment]
No, only on the last entry.
    name: "Buufed 2.0.1",
    summary: "Stable",
    device: "heroc",
    product: "Buufed",
    incremental: 201,
    modversion: "Buufed-2.0.1"

**Comment by bcrook** [comment]
Thats wrong though, because there is another field after it. gimme 5 min and i will fix yours up

**Comment by bcrook** [comment]
```
{
    version: 1,
    homepage: "http://crunchysoft.pocketdevelopers.com/",
    donate: "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T6GGP7T6NVV6Q",
    roms:
    [
    {
        name: "Buufed 2.0.1",
        summary: "Stable",
        device: "heroc",
        product: "Buufed",
        incremental: 201,
        modversion: "Buufed-2.0.1",
        screenshots:
        [
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom1.png"",
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom2.png"",
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom3.png"",
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom4.png"",
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom5.png"",
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom6.png"",
        "http://crunchysoft.pocketdevelopers.com/img/ss/rom7.png""
        ],
        urls:
        [
        "http://crunchysoft.pocketdevelopers.com/crunchyroms/Buufed-2.0.1.zip",
        "https://dl-web.dropbox.com/s/5kojzcgf9n0u4ae/Buufed-2.0.1.zip?dl"
        ],
        addons:
        [
        {
            name: "FCFix"
            urls:
            [
            "http://crunchysoft.pocketdevelopers.com/misc/patch/2.0.1-FC-Fixes.zip"
            ]
        },
        {
            name: "VisualVoicemail"
            urls:
            [
            "http://crunchysoft.pocketdevelopers.com//misc/patch/2.0.1-VVM-Fix.zip"
            ]
        }
        ]
    },
    // And here's another, older ROM!
    {
        name: "Buufed 1.7.2",
        summary: "Stable",
        device: "heroc",
        product: "Buufed",
        incremental: 172,
        modversion: "Buufed-1.7.2",
        urls:
        [
        "http://crunchysoft.pocketdevelopers.com/crunchyroms/Buufed-1.7.2.zip"
        ],
        addons:
        [
        {
            name: "VisualVoicemail"
            urls:
            [
            "http://crunchysoft.pocketdevelopers.com/misc/SprintVM.zip"
            ]
        }
        ],
        choices:
        [
        {
            name: "Kernel"
            options:
            [
            {
                name: "Overclocked"
                urls:
                [
                ""
                ]
            },
            {
                name: "Stable"
                urls:
                [
                ""
                ]
            }
            ]
        }
        ]
    }
    ]
}
```

**Comment by crunchysoft** [comment]
Okay, it's updated, thanks!

**Comment by crunchysoft** [comment]
a little off-topic.. 
when I choose any developer in ROM Manager it returns "Error occurred while processing the ROM list!"
Is there something wrong with the server, or something on my end?

**Comment by bcrook** [comment]
Something wrong on your end. I was trying to fix that with the commas

**Comment by bcrook** [comment]
can you take out those choices for the last rom, the empty ones?
        ,
        choices:
        [
        {
            name: "Kernel"
            options:
            [
            {
                name: "Overclocked"
                urls:
                [
                ""
                ]
            },
            {
                name: "Stable"
                urls:
                [
                ""
                ]
            }
            ]
        }
        ]

**Comment by crunchysoft** [comment]
Okay, I removed those entires.

Though Fresh and DamageControl do the same thing when I select them.

**Comment by bcrook** [comment]
Sorry, i was wrong about some of the commas, try this:
        {
        version: 1,
        homepage: "http://crunchysoft.pocketdevelopers.com/",
        donate: "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T6GGP7T6NVV6Q",
        roms:
        [
        {
            name: "Buufed 2.0.1",
            summary: "Stable",
            device: "heroc",
            product: "Buufed",
            incremental: 201,
            modversion: "Buufed-2.0.1",
            screenshots:
            [
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom1.png"",
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom2.png"",
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom3.png"",
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom4.png"",
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom5.png"",
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom6.png"",
            "http://crunchysoft.pocketdevelopers.com/img/ss/rom7.png""
            ],
            urls:
            [
            "http://crunchysoft.pocketdevelopers.com/crunchyroms/Buufed-2.0.1.zip",
            "https://dl-web.dropbox.com/s/5kojzcgf9n0u4ae/Buufed-2.0.1.zip?dl"
            ],
            addons:
            [
            {
                name: "FCFix"
                urls:
                [
                "http://crunchysoft.pocketdevelopers.com/misc/patch/2.0.1-FC-Fixes.zip",
                ]
            },
            {
                name: "VisualVoicemail"
                urls:
                [
                "http://crunchysoft.pocketdevelopers.com//misc/patch/2.0.1-VVM-Fix.zip",
                ]
            }
            ]
        },
        // And here's another, older ROM!
        {
            name: "Buufed 1.7.2",
            summary: "Stable",
            device: "heroc",
            product: "Buufed",
            incremental: 172,
            modversion: "Buufed-1.7.2",
            urls:
            [
            "http://crunchysoft.pocketdevelopers.com/crunchyroms/Buufed-1.7.2.zip",
            ],
            addons:
            [
            {
                name: "VisualVoicemail"
                urls:
                [
                "http://crunchysoft.pocketdevelopers.com/misc/SprintVM.zip",
                ]
            }
            ]
        }
        ]
    }

**Comment by crunchysoft** [comment]
done
(It should be encoded in ANSI, right?)

**Comment by bcrook** [comment]
Okay, there were a few errors and I gave you some bad advice lol, sorry.
http://pastebin.com/hNcynJ7x

**Comment by crunchysoft** [comment]
Sweet, that did it! Thanks bcrook!

**Comment by bcrook** [comment]
:D

**Comment by crunchysoft** [comment]
Any chance you can change the manifest from:
    {
        developer: "crunchybutternut",
        id: "Crunchybutternut",
        summary: "Fast and fully themed ROMs for the CDMA Hero.",
        manifest: "http://crunchysoft.pocketdevelopers.com/ROMManagerManifest/crunchysoft.js",
        roms:
        {
            heroc: true,
            free: true,
        }
    }
To:
    {
        developer: "crunchybutternut",
        id: "CrunchySoft",
        summary: "Fast and fully themed ROMs for the CDMA Hero by crunchybutternut.",
        manifest: "http://crunchysoft.pocketdevelopers.com/ROMManagerManifest/crunchysoft.js",
        roms:
        {
            heroc: true,
            free: true,
        }
    }

**Comment by crunchysoft** [comment]
You're the man!

**Comment by bcrook** [comment]
I think you want it to display CrunchySoft as the title, I changed it to this:
    {
        developer: "CrunchySoft",
        id: "crunchybutternut",
        summary: "Fast and fully themed ROMs for the CDMA Hero by crunchybutternut.",
        free: true,
        manifest: "http://crunchysoft.pocketdevelopers.com/ROMManagerManifest/crunchysoft.js",
        roms:
        {
            heroc: true

```
    }
}
```

Please note that free: true doesn't go under the roms: section.

**Comment by crunchysoft** [comment]
Okay, thanks!

**Comment by crunchysoft** [comment]
Hey, I know this is closed but just want to update my manifest.js to include another device and change the summary.
    {
        developer: "CrunchySoft",
        id: "crunchybutternut",
        summary: "Fast and fully themed ROMs for the CDMA Hero/HTC Evo by crunchybutternut.",
        free: true,
        manifest: "http://crunchysoft.pocketdevelopers.com/ROMManagerManifest/crunchysoft.js",
        roms:
        {
            heroc: true,
            supersonic: true,
        }
    }
