### ISSUE TITLE
Add ClearDroid to ROM Manager please

### ISSUE THREAD

**Issue by ClearD** [koush/ROMManagerManifest#294]
{
"developer": "ClearDroid",
"free": "true",
"id": "ClearD",
"icon": "http://www.techsupporteverything.com/cleardroid.png",
"manifest": "http://www.techsupporteverything.com/download/manifest.js",
"roms": {
"ace": "true"
},
"summary": "ClearDroid ROM for Inspire 4G. The most stable ROM available for the Inspire."
}

**Comment by koush** [comment]
Hi, please use this site now to sign up:

http://romshare.deployfu.com

It will let you use the free hosting, or just provide your own manifest as you did here.

**Comment by ClearD** [comment]
Will do, thank you very much. I have my own unlimited hosting site with unlimited bandwidth and all files already uploaded, so I will host the manifest there. :)

**Comment by koush** [comment]
Cool, then just use that the above site to link to your manifest, and it will use your own servers!

**Comment by ClearD** [comment]
Ok, my manifest is getting the error of: Error processing your manifest: "Unknown token after start:<"

I checked it, and it is JSON compliant... any idea how to fix this?

**Comment by koush** [comment]
Let me check your settings/.
