### ISSUE TITLE
ClearDroid ROM...

### ISSUE THREAD

**Issue by ClearD** [koush/ROMManagerManifest#295]
When trying to upload my JSON-compliant manifest.js, I get this error:

Error processing your manifest: "Unknown token after start:<"

Any idea what could be causing this? Thanks Koush
-Dustin

**Comment by DrMacinyasha** [comment]
Have you tried running it through jsonlint.com?

**Comment by ClearD** [comment]
Yes, it complies with JSON. No errors there... I even went through and double-checked my commas and brackets..

**Comment by ClearD** [comment]
Also, not sure if you need it or not, but the manifest is located here:

http://www.techsupporteverything.com/download/manifest.js

Should I post the code? :S

**Comment by DrMacinyasha** [comment]
That link is 404ing. I'd suspect that's the cause of your problem.

**Comment by ClearD** [comment]
Well, I think I just figured it out. The file I uploaded to my server was named "mainfest.js" and I was searching for "manifest.js".

For future reference, in case any coders are as ignorant as I am, that error apparently means it can't find the file it's looking for. ;)

**Comment by koush** [comment]
Hah, yeah it was probably parsing your 404 page.
