### ISSUE TITLE
Question about manifest.js

### ISSUE THREAD

**Issue by ClearD** [koush/ROMManagerManifest#297]
If anyone can answer this, I will be grateful. I am trying to edit the summary of my manifest file to use multiple lines (example: LeeDroid's ROM has about 7 lines of summary for the Ace) and I can't get it to work correctly. Is there some way to enter line breaks?

This is what I have been trying:

```
    "name": "ClearDroid 1.1.4",
    "summary": 
            [
            "Latest Stable Release.",
            "-1.84 OTA Base",
            "-Updated Installed Apps",
            "-Updated AngelDeath's GPS Mod"
            ],
```

However, that actually places the quotes and brackets in the summary for the ROM on ROM Manager. Is there a way to make it a single line with line breaks while still being JSON Compliant? And/Or how do other devs do this? Thanks!

-C|earD aka Dustin

**Comment by koush** [comment]
put a \n in your summary. \n means "new line"

**Comment by ClearD** [comment]
Thank you koush. I tried several things, including br / and was just confused. I'll drop a few in there!
