### ISSUE TITLE
Java Script for ROM Manager

### ISSUE THREAD

**Issue by smyers1012** [koush/ROMManagerManifest#299]
{
    "developer": "Smyers1012",
    "free": "true",
    "id": "smyers1012",
    "icon": "http://www.imm.io/7tWB",
    "manifest": "No Manifest",
    "roms": {
        "droidx": "true",
    },
    "summary": "These are my ROMs for the Droid X. I hope you enjoy them!"
   .
},

},

 "version": "1",

```
"homepage": "http://forum.xda-developers.com/showthread.php?t=1086148",

"donate": "https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=J7iFehv3cWuiy-YkOsb2dXdok-YOUp84bzxkIAEcPVLkTuyQVyblawfrJZW&dispatch=5885d80a13c0db1f8e263663d3faee8deaa77efc63a6eb429928d42bdf5d9d2c",

"roms": "GingerAle"
        "Detox Ginger"
[
{

    "name": "GingerAle 3.0",

    "summary": "Stable",

    "device": "droidx",

    "screenshot": "http://s1228.photobucket.com/albums/ee460/Myersmv9/?action=view&current=CAP201105291144.jpg&newest=1",

    "url": "http://www.mediafire.com/?1q27phrn8oz9363"
},

{
    "name": "Detox Ginger",
    "summary": "Stable",
    "device": "droidx",
    "url": "http://www.mediafire.com/?b6t449ehf3sziz2"
}
]
```

}

**Comment by koush** [comment]
can't use mediafire download links.
Also, please sign up at the ROM Manager developer portal http://romshare.deployfu.com
You can also get free hosting there.

**Comment by smyers1012** [comment]
I updated my info on that site but for some reason it won't let me upload the ROM..Is the server down or am I doing something wrong. I am filling in all the required fields! It keeps saying No data recieved on another page! and are you saying instead of mediafire I could use this site for a direct download or that I just can't use mediafire..Respond to this and I should be able to work everything out!
