### ISSUE TITLE
Want to be included in Rom Manager

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#30]
on you website it say open an issue.

here is my manifest

{
    developer: "InsaneNemesis",
    id: "InsaneNemesis",
    summary: "ROM's and Themes Built From Source",
    manifest: "https://dl.dropbox.com/u/8532412/InsaneNemesis.js",
    roms:
    {
        sholes: true,  
    }
}

i need to be in soon cause i want to release some time today and have everything ready.

**Comment by koush** [comment]
Done!
