### ISSUE TITLE
Request to be added to ROM Manager

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#303]
http://www.fzservers.com/protekk.js

**Comment by koush** [comment]
Use http://romshare.deployfu.com please! It's the new/easier way to get added to ROM Manager. You can also host your ROMs there too if you need.

**Comment by ghost** [comment]
On Sun, 31 Jul 2011 11:38:41 -0700, koush
reply@reply.github.com
wrote:

> Use http://romshare.deployfu.com please! It's the new/easier way to get
> added to ROM Manager. You can also host your ROMs there too if you need.

Using that service is there any way to get my ROMs in the Free section as
well or is it only going to be available to Premium users?  Btw, DeskSMS is
kick ass!

**Comment by koush** [comment]
Yep, if you host the ROMs yourself (using a manual manifest) they will _always_ be in the free section.

Otherwise, they will be in the free section 5 out of 7 days of the week. (The other two days, usually Saturday and Sunday, they are paid)
