### ISSUE TITLE
New server. can you update my manifest please

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#31]
i got rid of drop box(cause to much traffic) and will be using xeudoxus's server. can you update my manifest info.

{
    developer: "InsaneNemesis",
    id: "InsaneNemesis",
    summary: "ROM's and Themes Built From Source",
    manifest: "http://insanenemesis.xeudoxus.com/Insanely_Clean/InsaneNemesis.js",
    roms:
    {
        sholes: true,  
    }
}

thanks

**Comment by bcrook** [comment]
fixed in issue 32
