### ISSUE TITLE
Add Motorola Triumph WX435 Recovery

### ISSUE THREAD

**Issue by ikarosdev** [koush/ROMManagerManifest#311]
Hey Koush,

I've successfully ported CWM to the Motorola Triumph WX435. If my device configs are okay, I'd like to get the Triumph added to ROM Manager.

You can find my repo here: https://github.com/ikarosdev/android_device_motorola_triumph

I had to do these things for the port to work:
- Had to add 32 bit graphics.
- Add a custom keymapping
- Adjust the pagesize in /system/core/mkbootimg/mkbootimg.c from 2048 to 4096
- Not include recovery partition in fstab.

I've had many testers confirm that it works. They've successfully done a nandroid backup and restored. While working on CM7, I've flashed a zip just fine. However, USB mounting is not working.

Another big thing is that the device does not have a recovery partition. You have to put the phone in download mode and swap out the original recovery.img found in a fat partition at /dev/block/mmcblk0p1. In light of this, I've had to include custom releasetools. How will ROM Manager know to replace the image in /dev/block/mmcblk0p1? Is that something I need to do on my end?

Off-topic:

I had to manually change the pagesize in /system/core/mkbootimg/mkbootimg.c. Am I doing this wrong? If not, could we add a flag and build define so that way it'll be easier to have it build boot images for other devices that have a similar issue? For example: TARGET_USES_4K_PAGESIZE

Thanks,

Isaac

**Comment by koush** [comment]
You can define the pagesize in BoardConfig.mk. You shouldn't modify mkbootimg.

**Comment by koush** [comment]
Also, getting a build error:

target Prelink: libdl (out/target/product/triumph/symbols/system/lib/libdl.so)
build/tools/apriori/prelinkmap.c(100): build/core/prelink-linux-arm-2G.map:26 base 0x6ff00000 out of range.
make: **\* [out/target/product/triumph/symbols/system/lib/libdl.so] Error 1
make: **\* Waiting for unfinished jobs....

**Comment by playfulgod** [comment]
I seen where you said not to edit the mkbootimg.c for page size. But on the ascend with the unsigned pagesize = 2048 on line 109 it wont boot, but with it set at 4096 it will. It is set in the BoardConfig as 4096 but it wont boot unless the mkbootimg.c is edited to 4096. Whats the correct way of doing this if editing the mkbootimg.c isnt the correct way?

**Comment by iksteen** [comment]
mkbootimg takes a --pagesize <n> argument which can be either 2048 or 4096. That parameter is added to the argument list in system/core/Makefile if BOARD_KERNEL_PAGESIZE is set in BoardConfig.mk.

So "BOARD_KERNEL_PAGESIZE := 4096" in the BoardConfig.mk should be enough.

**Comment by playfulgod** [comment]
ahhh Thank you!!!!

**Comment by koush** [comment]
@iksteen is correct.

Please let me know once you have fixed that and the build error.

**Comment by ikarosdev** [comment]
@koush

I have that set in my BoardConfig.mk already. I'm not sure about the build error. I'm not getting an error when I build...

**Comment by koush** [comment]
Are you fully synced with CyanogenMod?

**Comment by ikarosdev** [comment]
TBH, I haven't built anything in a couple weeks, but I never got that error. (I'm just using the standard prelink 2G map). In any case, this weekend I will resync and check to see if the error is present. 

In regards to my question in my OP, does ROM Manager have the capabilities to swap out the stock recovery for CWM? It's just a simple mount /dev/block/mmcblk0p1, replace, and unmount. There isn't anything that needs to be done on my end, correct?

**Comment by koush** [comment]
Does the phone need to be in download mode to access  /dev/block/mmcblk0p1?

Why can't I do that from a booted android system?

**Comment by ikarosdev** [comment]
No, it shouldn't. I was just asking out of curiosity.

I picked a bad day to try and sync (repos are down), but libdl is being built just fine:

target Prelink: libdl (out/target/product/triumph/symbols/system/lib/libdl.so)
Install: out/target/product/triumph/recovery/root/sbin/e2fsck
Install: out/target/product/triumph/recovery/root/sbin/fix_permissions
Install: out/target/product/triumph/recovery/root/sbin/killrecovery.sh
Install: out/target/product/triumph/recovery/root/sbin/mke2fs
Install: out/target/product/triumph/recovery/root/sbin/nandroid-md5.sh
Install: out/target/product/triumph/recovery/root/sbin/parted
Install: out/target/product/triumph/recovery/root/sbin/sdparted
Install: out/target/product/triumph/recovery/root/sbin/tune2fs
DumpPublicKey: out/target/product/triumph/obj/PACKAGING/ota_keys_intermediates/keys <= build/target/product/security/testkey.x509.pem
target Strip: libdl (out/target/product/triumph/obj/lib/libdl.so)
java -jar out/host/linux-x86/framework/dumpkey.jar build/target/product/security/testkey.x509.pem > out/target/product/triumph/obj/PACKAGING/ota_keys_intermediates/keys
Install: out/target/product/triumph/system/lib/libdl.so

I don't know why you're getting that compile-time error.

EDIT: Sorry, didn't mean to close the issue.

**Comment by ikarosdev** [comment]
Koush,

Updated and fully-synced. No errors when building a recovery image.

**Comment by ikarosdev** [comment]
What's the status of this? Everything is building and working fine here. Users have been using the latest unofficial build (5.x.x.x) just fine.

**Comment by ziggy46** [comment]
yep the v5.x.x.x build works fine. and like isaac said, would rom manager be able to unmount the partition and access it to replace the recovery image? (simiar to the "umount" command in a terminal)

**Comment by ikarosdev** [comment]
It should also be noted that the Triumph uses the same process as the U8800 in replacing the recovery:

1) mount -o remount,rw -t vfat /dev/block/mmcblk0p1 /MOBILE

2) Copy the new recovery to /MOBILE/image/recovery.img

**Comment by evanrobinson1985** [comment]
Koush, 

What is the status on this..?  I have been following it for a while now and have seen no progress in almost a month. There are quite a few roms available out there. And furthermore, there is currently a long line of people hoping that you will add this soon. I have already purchased rom manager for my optimus v, but since I upgraded to the triumph your program has been useless and I have had to do everything manually. I am willing to make a generous donation to help with your troubles as soon as it is added. I love your app and would like to continue using it. Thank you in advance.

**Comment by lifeblows10** [comment]
I too would love to see this on ROM Manager.... when will the Triumph see some love???

**Comment by ziggy46** [comment]
Koush,

i have successfully built the ClockworkMod recovery for this device personally. (and im a complete newb when it comes to source building) So you shouldnt be having any problems with building this. Would you please try again and consider adding this phone to your app?

**Comment by koush** [comment]
make: **\* No rule to make target `hardware/qcom/gps/loc_api/libloc_api-rpc/inc-50001/loc_api_cb.h', needed by`out/target/product/triumph/obj/include/libloc_api-rpc/inc/loc_api_cb.h'.  Stop.
make: **\* Waiting for unfinished jobs....
Header: out/target/product/triumph/obj/include/librpc/rpc/xdr.h

**Comment by koush** [comment]
Keep in mind, I am building against the cyanogenmod tree.

**Comment by ikarosdev** [comment]
Koush,

The guy I'm working with and I have made significant changes to the CM tree. We've forked numerous repos and made our own changes. I believe most of the changes we made will _not_ break other devices, but in this particular case, it will. Since the AMSS 50001 protocol is not found in CM's qcom_gps repo, we were forced to grab it from CAF.

**Comment by koush** [comment]
@ikarosdev You should submit those changes to gerrit so we can have it in CM, and then I can build recovery properly.

**Comment by playfulgod** [comment]
add in the 6225 too please lol

**Comment by ikarosdev** [comment]
@koush I don't have time ATM. Can you just comment out the offending lines?

@playfulgod No, AMSS 6255 support was removed for a reason.

**Comment by koush** [comment]
I have no idea what the offending lines are, and I don't have time to fix other people's code :/

**Comment by ikarosdev** [comment]
If you have the current device configs from my repo, this _should_ work.

Set BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50001

to

BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 50000

Comment out:
BOARD_VENDOR_QCOM_GPS_NEEDS_LNA := true
BOARD_VENDOR_QCOM_GPS_HAS_BROKEN_XTRA := true

These 3 lines are the only new changes different from upstream.

**Comment by ghost** [comment]
CM7 has NOT deigned to include AMSS 50001 support in their upstream.  As a result the changes in qcom_gps are extensive.  If and when CM7 decides to include AMSS 50001 we can use it with either very small or (probably) no changes at all.

However, this is not currently the case and there is no "fast" way to fix that, just as there is no official support in the RIL code for the Triumph either, nor for the Camera (which is an odd bastardization compared to the other devices that "just work.")  All of these have explicit support in the repos that I (and Isaac) forked which means the manifest is different from the stock CM7 one and I have little if any expectation that the CM7 people will pick that up; Isaac has been trying to get them interested in it for a good long while and my understanding is that he's been basically ignored.

**Comment by koush** [comment]
I'll try that @ikarosdev.

**Comment by Chairshot215** [comment]
It would be nice to see Rom Manager working on the Triumph. Based on the thousands of views the Rom posts are receiving over on Android Forums I’m guessing that if only 5% of those people purchased the premium version you would be looking at a decent return on any time spent, Even more so after X-mas. If a decade as an Electronics manager for Target has taught me anything it’s the ability to recognize what is going to sell and this phone is going to move like hotcakes over the next couple of month as it will be on many a 16-24 year old wish lists.

**Comment by lifeblows10** [comment]
Any word on the status of this?

**Comment by ziggy46** [comment]
are we going to see this anytime soon? or is this dead?
