### ISSUE TITLE
Recovery for the Huawei Ascend 2 M865

### ISSUE THREAD

**Issue by playfulgod** [koush/ROMManagerManifest#312]
Hello koush,

I have ported CWM recovery to the Huawei Ascend 2 M865  and have had it tested and verified as working fully. If you could merge this at your earliest convenience I would greatly appreciate it.

My repo:

https://github.com/playfulgod/android_device_huawei_ascend2

And again thanks for your time I know you're a busy man, and thanks for the suggestions on the keybindings.

Dewayne

**Comment by koush** [comment]
board init is init.qcom.rc?

Recovery is build and published. Let me know if it shows up or not.

**Comment by playfulgod** [comment]
yes its init.qcom.rc and is reported to show up, thanks!!!!

**Comment by Dunhamer** [comment]
hey I had a question regarding my ascend2.. I have tried flashing cwm recovery and  its says download successful but I cant boot into recovery. I just get the huawei symbol. my phone is rooted and everything else works fine. I want to install the a2 tude  rom but I can't since it won't let me load into recovery to install. Please help

**Comment by playfulgod** [comment]
did you make sure you installed the CWR for the Ascend 2 and not for the Ascend?

**Comment by Dunhamer** [comment]
Yessir. I tried many many times. I'm spoofed.

**Comment by playfulgod** [comment]
yea, me too, as many others have used it w/o issue lol

**Comment by Dunhamer** [comment]
Could it be I'm using a 3 g connection and  not a wifi to download it?

**Comment by koush** [comment]
Yes, i recommend being on wifi.

**Comment by playfulgod** [comment]
Yes, very possible to be getting a corrupted dl that way, esp on metro lol

**Comment by playfulgod** [comment]
oh wait, A2 on cricket my bad lol, but still use wifi ;)

**Comment by Dunhamer** [comment]
If it doesn't work?

**Comment by playfulgod** [comment]
Have you tried pressing the flash CWR twice?
