### ISSUE TITLE
Recovery for the LG Optimus C LW690

### ISSUE THREAD

**Issue by playfulgod** [koush/ROMManagerManifest#313]
Hello koush,

I have built a recovery for the LG Optimus C LW690. I have had it tested and verified working. My repo for it is at: 

https://github.com/playfulgod/android_device_lge_thunderc

Please merge when you get a chance.

Thanks,

Dewayne

**Comment by koush** [comment]
I already have a thunderc repo and recovery published? Does it not work?

**Comment by playfulgod** [comment]
I was informed there wasnt a recovery for the LW690 which is the Cricket version. And I didnt see one one listed for it in ROM Manager for the LW690 b4 I flashed the one I ported. I believe you have one for the LS670 which is the Sprint version and one or the VM670 which is the Virgin Mobile version.

Theres 4 or 5 variants and each seem to have different partition sizes than the other with the exception of the Cricket LW690 and the MetroPCS MS690 which are the same and the port I did should work on both.

**Comment by koush** [comment]
Ack. I'm already using the "thunderc" key. This will cause issues. So recoveries are not compatible between devices?

**Comment by playfulgod** [comment]
Only with the LW690 and MS690 by what I see of the partition sizes. On my CM7 port I can add LW690-MS690 in the name of the init.thunderc.rc, but that wouldnt help the stock users would it?

I would need to find a OM owner to verify it works for them too, though I dont see any reason why it shouldnt.

**Comment by koush** [comment]
partition sizes should not affect anything though. just the partition locations (ie, mmcblk1p1, mtdblock6, etc)

**Comment by koush** [comment]
oh i see, different kernels. nevermind.

**Comment by playfulgod** [comment]
yea lol

**Comment by playfulgod** [comment]
Just had it verified that this recovery will work on the Optimus M MS690 too.

**Comment by playfulgod** [comment]
Hey koush,

I had to edit n rebuild this recovery so usb storage worked from recovery. Tested and is working now.

Only issue I know of is the E:Bad boot message "recovery" which with a lil googling I found to be a issues with a LG process that auto-reboots recovery or some bs like that.

And more reports verifying this recovery works great on both the Optimus C LW690 and M MS690

**Comment by koush** [comment]
Are you sure this is known as thunderc?

**Comment by playfulgod** [comment]
Yes sir, I can send you the stock files if you want to look at em. They both have init.thunderc.rc in the boot.img.ramdisk.

Oh and all recoveries going to be updated to 5.0..0.5??

**Comment by playfulgod** [comment]
they both have init.qcom.rc too if that helps.

**Comment by playfulgod** [comment]
Any clues on this one yet??

**Comment by koush** [comment]
I'll give it another go soon

**Comment by playfulgod** [comment]
oops, sorry didnt mean to close this lol.

K, thanks, I know ya a busy man ;)

**Comment by koush** [comment]
arcee: # 2.1 LG Optimus C - LW690 - Cricket
[12:08am] arcee: # 2.2 LG Optimus M - MS690 - MetroPCS
[12:08am] arcee: # 2.3 LG Optimus S - LS670 - Sprint
[12:08am] arcee: # 2.4 LG Optimus T - P509 - T-Mobile USA
[12:08am] arcee: # 2.5 LG Optimus U - US670 - US Cellular
[12:08am] arcee: # 2.6 LG Optimus V - VM670 - Virgin Mobile USA
[12:08am] arcee: there you go. 
[12:08am] koush: what a trainwreck
[12:09am] arcee: # 2.8 LG Vortex - VS660 - Verizon Wireless
[12:09am] arcee: ah, missed one

**Comment by playfulgod** [comment]
yup and each but the LW n MS690 have different partition sizes far as I know. :\

**Comment by playfulgod** [comment]
any update on this yet?

**Comment by playfulgod** [comment]
any word on this yet?

**Comment by koush** [comment]
Since I already have a thunderc device, this needs to be named something else. Maybe according to the model number, like 
android_device_lge_lw690

**Comment by playfulgod** [comment]
K, I renamed it android_device_lge_lg690 since it covers the LW690 and MS690. Repo located at:

https://github.com/playfulgod/android_device_lge_lg690

**Comment by koush** [comment]
You need to rename the stuff in the makefile too, or it wont build.

**Comment by playfulgod** [comment]
yea, sorry about that derp lol

**Comment by playfulgod** [comment]
edited and did a test build, all seems to build n work fine. ;)

Should be all set.

**Comment by playfulgod** [comment]
any update on this yet?

**Comment by koush** [comment]
ok, it builds.

Can you give me a file in the ramdisk i can find to list the device in the list of possible devices when flashing recovery?

**Comment by koush** [comment]
I've published the recovery as

LG Optimus C LW690

Let me know if it does not show up, that means it is a detection problem.

**Comment by playfulgod** [comment]
Hey, sorry for the late reply been busy with getting cwm working on the lg esteem. Stock will have init.thunder.rc in it and my cm7 port should have qcom, I will have to dbl check now....

k, according to my device mk file it should have init.thunder.rc and thanks to a typo, a init.qcom.thunderc.rc in the ramdisk. My next build I will correct the type so its named init.qcom.rc. 

Also just got it confirmed it shows up. It also works on the Optimus M MS690 if you can have it show too would be great.

Also on the esteem I have a issue with cwm rebooting 2 minutes in, do I open a new issue for it?

Again thanks;

Dewayne
