### ISSUE TITLE
Recovery for the Micromax A70

### ISSUE THREAD

**Issue by playfulgod** [koush/ROMManagerManifest#314]
Hello koush,

I have another recovery ported and ready to be merged when you get a chance. This one is for the Micromax A70, my repo for this is at:

https://github.com/playfulgod/android_device_micromax_a70

Thank you,

Dewayne

**Comment by playfulgod** [comment]
Hold on this one, going to have to add a recovery_ui. Will reply back when ready here in a few.

**Comment by playfulgod** [comment]
K this is a go, when you get to it.

**Comment by koush** [comment]
Alright. I'm getting a bit behind with all these new recovery ports. I'll try to get to them soon.

**Comment by playfulgod** [comment]
K, thanks and much appreciated.
On Aug 22, 2011 9:28 PM, "koush" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
init.****.rc? What ramdisk file can I use to identify the device?

**Comment by koush** [comment]
It is now in rom manager, but it may not show up unless I have the correct init file listed.

**Comment by playfulgod** [comment]
I have the ramdisk extracted and it has a init.qcom.rc, init.goldflish.rc (which I didnt see anything in to id it), init.rc, and init.

will any of those work and do I need to upload it?

**Comment by playfulgod** [comment]
Yea according to your comment on the M865, the init.qcom.rc should be correct.

I will leave a comment here when I see the one A70 user I know of if it shows in ROM Manager.

**Comment by playfulgod** [comment]
I see it in RM so this should be good to go.

Thanks
