### ISSUE TITLE
Recovery for Samsung Galaxy Indulge SCH-R910

### ISSUE THREAD

**Issue by DRockstar** [koush/ROMManagerManifest#316]
Koush,

Thanks for bearing with me as I learn the right way of doing things without bugging you too much ;) Anyways, here is the first of 2 ports, this one is for the Samsung Galxy Indulge SCH-R910 on MetroPCS.

https://github.com/DRockstar/android_device_samsung_indulge910

There is the device tree... I'm still working on kernel implimentation, as the samsung source was unbuildable until just recently. It appears the recovery partition isn't used, and due to this, I've implimented a fakeflash cwm redirector from /system/bin/recovery where recovery was replaced by a redirector script.

The device tree has been tested working with the latest source... this device should allow you to do updates through ROM Manager.

Also of note: init.smdkc110.rc is the only file type like the one you requested before.

Let me know if I need to do anything else.

Thank you,

DRockstar
Donovan Bartish

**Comment by koush** [comment]
So this is fakeflash right? I release a zip?

**Comment by DRockstar** [comment]
Yes, fakeflash for now, I appreciate it!

**Comment by DRockstar** [comment]
Duh, such a github noob I am ;)

**Comment by DRockstar** [comment]
That's what I get for commenting on my phone! LOL

**Comment by koush** [comment]
Should be done, please check.

**Comment by DRockstar** [comment]
things are looking good for this, thank you!
