### ISSUE TITLE
Recovery for Samsung Galaxy Indulge SCH-R915

### ISSUE THREAD

**Issue by DRockstar** [koush/ROMManagerManifest#317]
Koush,

This one is for the Samsung Galaxy Indulge SCH-R915 on Cricket.

https://github.com/DRockstar/android_device_samsung_indulge915

There is the device tree... I'm still working on kernel implimentation, as the samsung source was unbuildable until just recently. It appears the recovery partition isn't used, and due to this, I've implimented a fakeflash cwm redirector from /system/bin/recovery where recovery was replaced by a redirector script.

The device tree has been tested working with the latest source... this device should allow you to do updates through ROM Manager.

Also of note: init.smdkc110.rc is the only file type like the one you requested before.

Let me know if I need to do anything else.

Thank you,

DRockstar
Donovan Bartish

**Comment by DRockstar** [comment]
Fakeflash for this one too...

**Comment by koush** [comment]
Shoiuld be done, please check.

**Comment by DRockstar** [comment]
things are looking good, thank you!
