### ISSUE TITLE
NSCollab removed?

### ISSUE THREAD

**Issue by frank707** [koush/ROMManagerManifest#319]
NSCollab has been removed from the rom manager listing for Nexus S devices. 

http://studiousmedia.com/crespo/nsmanifest.js

**Comment by koush** [comment]
Probably accidental, when I ran the health check, it may have failed. 

Are you the dev? Can you readd it to http://romshare.deployfu.com. It should only take a second. Sorry for the trouble! The health checker can be quite unforgiving. Adding it to ROM Share will prevent it from being deleted again.

Koush

**Comment by frank707** [comment]
No worries. Thanks for the supports. How long will it take before its visible in rom manager?

**Comment by koush** [comment]
I just ran the health check again. It seems your manifest is malformed still. Please run your stuff through JSON Lint (google it).

Ie, not:
name: "my rom"

instead, use:
"name": "my Rom"

etc.

Koush

**Comment by frank707** [comment]
updated should be fixed.

**Comment by koush** [comment]
No, I mean in your actual manifest at:
http://studiousmedia.com/crespo/nscollab.js

**Comment by koush** [comment]
Please run that through JSON lint and fix the errors.
The reason for the change is that ROM Manager will have a webpage soon, and if it is not valid JSON, the ROM will not be viewable in the webpage.

**Comment by koush** [comment]
I have fixed it for you. Please upload it to your site:

http://download.clockworkmod.com//test/stuff.txt

**Comment by frank707** [comment]
sorry was away. didn't run it through JSONlint first time around, but thanks for the help again. Have uploaded the files on my server accordingly.

**Comment by koush** [comment]
Cool, fixed.
