### ISSUE TITLE
My Manifest is Down because of Drop Box. Need to have my Links updated 

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#32]
my dop box failed i posted this issue earlier and havent seen a fix. heres the info i need updated.

{
    developer: "InsaneNemesis",
    id: "InsaneNemesis",
    summary: "ROM's and Themes Built From Source",
    manifest: "http://insanenemesis.xeudoxus.com/Insanely_Clean/InsaneNemesis.js",
    roms:
    {
        sholes: true,  
    }
}

all i need switched is the dl.dropbox link to insanenemesis.xeudoxus.com link. 

thanks

**Comment by bcrook** [comment]
so sorry, give me 2 min

**Comment by ghost** [comment]
ok thanks. im sorry just dont want it to be down to long. lol. thanks again

**Comment by bcrook** [comment]
k, should be done

**Comment by ghost** [comment]
thanks
