### ISSUE TITLE
Ascend 2 not booting into recovery cwm flashed but still no recovery mode

### ISSUE THREAD

**Issue by Dunhamer** [koush/ROMManagerManifest#325]
Flashed cwm still no recovery.. Trying to install a2tude. when I reboot to install only the huawei symbol shows up. Phone works.fine otherwise. Please help all comments greatly appreciated.

**Comment by playfulgod** [comment]
you're booting into fastboot and not recovery ;) and you're the only one thats posted having this issue ;)

**Comment by Dunhamer** [comment]
Lol I tried it on wi fi too still no dice

**Comment by playfulgod** [comment]
I've been playing with this on a loaner A2 for 2 days now and it works flawlessly. ;)
