### ISSUE TITLE
Add Samsung GT-S5570 (Galaxy Mini) Recovery

### ISSUE THREAD

**Issue by tjstyle** [koush/ROMManagerManifest#328]
Hello Koush..

Can you add support  Rom Manager for Galaxy Mini?

You can find the device config in here:
https://github.com/teamhacksung/android_device_samsung_tass

All feature is working find..

Thank you..

**Comment by koush** [comment]
Awesome, i'll take a look when i get home

**Comment by koush** [comment]
Done, please test.

**Comment by tjstyle** [comment]
tested and working fine for stock roms (rfs).
but can't be used for ext4 based roms.
actually, no one galaxy mini users that using clockworkmod for stock roms, only using for ext4 based roms like cm7 for galaxy mini.
so, are is better to stop support for rfs, and continue to using ext4 in fstab?

Thank you..
