### ISSUE TITLE
Huawei u8800 recovery

### ISSUE THREAD

**Issue by stockwell** [koush/ROMManagerManifest#329]
Hi Koush,

Would you be able to have a look at my device config and add support for this device to rom manager?

It is available here: https://github.com/stockwell/android_device_huawei_u8800

The only thing I'm not sure about is that our device doesn't have a recovery partition, there is just a vfat filesystem that contains the recovery and boot images. I guess instead of flashing to a partition using dd or whatever it would have to remount it as writeable and then copy it to the correct location.

Let me know, thanks.
Stockwell.

**Comment by koush** [comment]
ROM Manager supports this. Just let me know the exact commands necessary to mount and copy the image into place.

**Comment by stockwell** [comment]
Okay that was quick. Everything works fine, thanks Koush.

**Comment by stockwell** [comment]
Sorry to reopen this, I didn't realise that the recovery wasn't actually being installed when it rebooted into it lol.

So the image will be copied across from fakeflash then, is that correct?

The commands for this will then be:
mkdir /boot
mount /dev/block/mmcblk0p1 /boot

Then it should be copied to /boot/image/recovery.img

Thanks Koush.

**Comment by stockwell** [comment]
One other thing is that stock devices uses init.huawei.rc instead of init.u8800.rc. Is it possible to use both to identify the device?

**Comment by koush** [comment]
No, must use one or the other.

**Comment by koush** [comment]
I'll adjust the flashing process so it really flashes then.

**Comment by koush** [comment]
What is the file system type on /boot? I will need to specify it with the -t argument to mount.

**Comment by stockwell** [comment]
Filesystem is vfat.

**Comment by stockwell** [comment]
Just to be clear, this will be done from recovery right? 

Actually thinking about that it can't be correct as the stock recovery won't boot fakeflash, so would only work on devices which already have cwm recovery..

If it's done from android then it's slightly different, because /boot is already mounted (for whatever strange reason it's mounted to /cust_backup)

So it just needs to be remounted as writeable:
mount -o remount,rw -t vfat /dev/block/mmcblk0p1 /cust_backup

Then the image copied to /cust_backup/image/recovery.img

Sorry for my extreme noobness on this!

**Comment by koush** [comment]
The flash from ROM Manager will be done from Android. Not recovery.

**Comment by stockwell** [comment]
Okay thanks lol the whole fakeflash thing really threw me off.

So yeah, just the commands to do the flashing as above would be excellent. Again thanks for your patience with me.

**Comment by stockwell** [comment]
Hi Koush, I know you're a busy man, but is there any chance of getting this switched over to properly flashing?

Thanks!

**Comment by koush** [comment]
Ok done, sorry for the extreme delay! Let me know if it worked.
