### ISSUE TITLE
cvpcs sapphire manifest

### ISSUE THREAD

**Issue by cvpcs** [koush/ROMManagerManifest#33]
{
    developer: "cvpcs",
    id: "cvpcs",
    summary: "Source-based mods made by CVPCS",
    manifest: "http://sapphire.cvpcs.org/files/other/cvpcs-rmm.js",
    free: true,
    roms:
    {
        sholes: true
    }
}

**Comment by bcrook** [comment]
i added it but your manifest is failing - I can't tell why. Maybe koush can see something...

**Comment by cvpcs** [comment]
i took a look. there was an error in my manifest file on my end.  the addition you made is valid.  i fixed the problem on my end so it shouldn't be an issue

**Comment by bcrook** [comment]
Poifect.
