### ISSUE TITLE
Default to EXT4 for Galaxy Mini GT-S5570

### ISSUE THREAD

**Issue by tjstyle** [koush/ROMManagerManifest#333]
Hi, Koush..
The current Clockworkmod Recovery for Galaxy Mini is working fine for RFS based (Stock ROMs).
But users is using Clockworkmod Recovery is for EXT4 based ROMs.
For Backup, Restore and install CM Roms on Galaxy Mini.

So i've change the recovery.fstab to only support EXT4, and let odin to support RFS based ROMs.
You can take the last commit for device config in here:
https://github.com/teamhacksung/android_device_samsung_tass

And also I've upload to gerrit about requesting Galaxy Mini to be merged on mainline CM, need your review here:
http://review.cyanogenmod.com/#change,8469

You can see the info about CM ROMs for Galaxy Mini in this thread:
http://forum.xda-developers.com/showthread.php?t=1167750
All Hardware is working except USB Tether, Hope you and all CM team can approve and merging the Galaxy Mini to mainline.

Thank you very much..

**Comment by Squadzone** [comment]
bump ^^

**Comment by Squadzone** [comment]
new config here
http://review.cyanogenmod.com/13916

please help us to support ROMmanager :)
