### ISSUE TITLE
ROM Manager Developer Portal

### ISSUE THREAD

**Issue by frank707** [koush/ROMManagerManifest#334]
Rom manager has been working great for my rom release on the crespo. I updated my manifest to include a series for the crespo4g but based on the users feedback it doesn't seem to be appearing under rom manager for that device. I have my developer portal setup to use this manual manifest: 

http://studiousmedia.com/crespo/nscollab.js

**Comment by koush** [comment]
Yeah, adding a new device takes a bit to show up. It should be there now.
