### ISSUE TITLE
Please add CWM support for Huawei U8160 (a.k.a. Vodafone Smart VF858)

### ISSUE THREAD

**Issue by psyke83** [koush/ROMManagerManifest#337]
Hey koush,

Can you add official CWM support for the Huawei U8160?

Here's my build tree (it's also got fully-functional CM7 support): https://github.com/psyke83/android_device_huawei_u8160

My unofficial CWM builds have been used for some time without issues:
http://forum.xda-developers.com/showthread.php?p=17496969

Thanks!
psyke83 

P.S. The U8160 kernel has support for multiple Huawei msm7225 (i.e. U81xx) devices, so this CWM build could probably work on other devices (including the Ideos U8150). Although not strictly relevant, my device tree only has 100% support for the U8160 and U8180 in CM7. Other devices work partially, but have various problems such as non-functional Bluetooth, wifi, etc. The MTD layout may also differ slightly on these phones.

**Comment by koush** [comment]
Done
