### ISSUE TITLE
add to RomManager master manifest

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#344]
Developer JavaScript file:
http://dl.dropbox.com/u/49321219/GingerXTBR.js

To enable the manual manifest to my ROM is hosted in the
free section.

Thanks
Heitor

**Comment by koush** [comment]
Oh, ROM Manager doesn't need this anymore. Please use http://developer.clockworkmod.com to sign up. You can host your ROMs on the developer site too, or use your ROM list manifest that you have contained in this file.

**Comment by ghost** [comment]
Ok, thanks
