### ISSUE TITLE
You notify me and issue with my repo

### ISSUE THREAD

**Issue by shawe** [koush/ROMManagerManifest#35]
This must be my new URL manifest that you say me that don't work correctly in the past. I see that this error only ocurre with Froyo because URL have a "%20", now using a "_". Please can you update it?

```
manifest: "http://content.wuala.com/contents/shawe_ewahs/Publica/Android/ROM_Manager/manifest.js",
```

**Comment by bcrook** [comment]
Done. :)

**Comment by shawe** [comment]
Thanks a lot :D

**Comment by shawe** [comment]
I can't get my list of ROM's now, I don't found that I do wrong.

**Comment by bcrook** [comment]
Try deleting the square brackets on line 381 and 394

**Comment by shawe** [comment]
Now works, problem for copy&paste code :P
