### ISSUE TITLE
Add support to epicmtd

### ISSUE THREAD

**Issue by shareefalis** [koush/ROMManagerManifest#350]
We switched our cyanogenmod branch to MTD and we would like to make a section for epicmtd to avoid any conflict with BML versions
It uses yaffs2 and mtd
 our device config: https://github.com/EpicCM/android_device_samsung_epicmtd

**Comment by shareefalis** [comment]
We use this as a  recovery command
TARGET_RECOVERY_PRE_COMMAND := "/system/xbin/busybox devmem 0x57fff800 32 0x5EC0B007; sync"

**Comment by koush** [comment]
done. please let me know if reboot recovery does not work.

**Comment by shareefalis** [comment]
no it doesn't work because we use this as a recovery command.. TARGET_RECOVERY_PRE_COMMAND := "/system/xbin/busybox devmem 0x57fff800 32 0x5EC0B007; sync"
