### ISSUE TITLE
LG Esteem MS910

### ISSUE THREAD

**Issue by playfulgod** [koush/ROMManagerManifest#351]
Hello koush,

Its me again working on another port for the LG Esteem. We have at least one issue that keeps us from testing it fully. It reboots about 2 minutes after being booted into CWM. I have check the recovery.log and all it shows is the file EXTENDED_COMMAND wasnt found, which we discovered other devices get this error too. Find the same error is recovery/lastlog. Which is no help as to what the problem is. My repo is at:

https://github.com/playfulgod/android_device_lge_esteem

Any help or insight is appreciated.

Thanks,

Dewayne

**Comment by playfulgod** [comment]
k have the reboot issue resolved and most functions working correctly. Issues remaining are, boot not listing in mounts and storage, USB Mass Storage not working (prolly incorrect path), fix permissions doesnt seem to do anything, and performing a factory reset from the OS > settings doesnt work correctly (still investigating). other than that just when booting into CWM with the button combo the LG reset screen comes up first, still looking on how to fix that.

Any insight will be appreciated so we can get this ready to submit for you to make it official. ;)

Thanks,

D

**Comment by playfulgod** [comment]
ok think this is ready to submit now. Only thing really not working is USB Mass Storage, which isnt a real biggie IMO. lol

Thanks

D

**Comment by sos987** [comment]
Hello playfulgod
I am trying to port CWM for ZTE V9+ device and same problem appears - CWM is rebooting after 2.5 mins.
Could you please tell how have you fix that?

**Comment by playfulgod** [comment]
I compiled a kernel just for recovery with rmt_storage not set in the defconfig. You can also try editing the init.*.rc and comment out the line referencing rmt_storage to see if it helps in your case.

**Comment by ivan19871002** [comment]
rmt_storage issues
https://github.com/Blefish/android_device_huawei_u8800/issues/1

**Comment by sos987** [comment]
By the way, if i'll exclude from recovery init.rc line about rmt_storage, will it help? (i've already tried - same problem)

**Comment by playfulgod** [comment]
try it and see. Only other way I know to work around it is compiling a new kernel if src is avail or by doing what it says in that link ivan posted.

**Comment by playfulgod** [comment]
@koush, anything need done to this so you can do an official build for it? We been using 5.0.2.7 with no major issues.

**Comment by sos987** [comment]
@playfulgod sorry man, already tried - it doesn't help. Also, ZTE haven't released our kernel sources, so I think, I'm stuck=(

**Comment by koush** [comment]
@playfulgod Ok, just built this. Have you started building off the ICS tree yet for recovery? I'll be switching to that soon.

**Comment by playfulgod** [comment]
Yea, it builds, boots, and seems to work fine, but wont boot into the os, just bootloops back to CWM. I've not investigated the cause of that much as my CM9/ICS port is going slow.

Any clues as what it may be or what I need too look for or do?

**Comment by playfulgod** [comment]
@koush,

Its not showing up in ROM Manager. Stock init was qcom and we been using bryce with CWM n CM. I can change it n start using esteem in my builds, but that wont help with stock roms will it?

**Comment by koush** [comment]
init.qcom.rc and init.bryce.rc?

**Comment by playfulgod** [comment]
yup that be them.

**Comment by playfulgod** [comment]
Stock had init.qcom.rc and my CM\* port I am using init.bryce.rc, bryce is LG's code name for it and its Verizon cousin the Revolution. Recoveries and ROMs arent compatible between the 2 tho.

**Comment by playfulgod** [comment]
Believe I found why the ICS tree CWM wont boot into the OS. My CM9 tree doesnt have a AndroidBoard.mk which calls the postrecovery.sh thats needed. Testing this now n will update you. If this is the issue, how is it suppose to be done with ICS/CM9 since it doesnt use the AndroidBroad.mk?

**Comment by playfulgod** [comment]
@koush,

K That was the issue and a PRODUCT_COPY works to load it. Have an issue with it building with 'make recoveryimage' tho. It gives the error

build/core/Makefile:111: **\* BUILD_FINGERPRINT cannot contain spaces: "Android Android/full_esteem/esteem:4.0.3/MR1/eng.playfulgod.20120201.140726:eng/test-keys".  Stop.

But builds fine with brunch etc, and everything seems to work great with the exception of USB Mass Storage which is something with my config on either tree.

**Comment by koush** [comment]
The newest ROM Manager will now check for the following files:

init.qcom.rc and init.bryce.rc

**Comment by playfulgod** [comment]
Shows now! Thanks!! :)
