### ISSUE TITLE
RomManager master manifest 

### ISSUE THREAD

**Issue by thonatos** [koush/ROMManagerManifest#354]
I just create a js script for RomManager .

http://www.just-for-you.org/thonatos/adds/manifest.js

but rom is still being uploading . you can find more imformation about me ...

(But i am sorry to say that I am a chinese and my blog is writen by CHS ...)

**Comment by koush** [comment]
Hi, please sign up at http://developer.clockworkmod.com.

You can provide all your information and manifest links there now. Much easier.

**Comment by thonatos** [comment]
hah , I already hava a account at there , and I also have done that .

**Comment by thonatos** [comment]
thank you very much , i have solved the problem . it is ok now .

**Comment by koush** [comment]
Great
