### ISSUE TITLE
Add official CM epicmtd device to ROM Manager for Epic4G

### ISSUE THREAD

**Issue by DRockstar** [koush/ROMManagerManifest#355]
Here's the device files, it's been merged into cm official now:

https://github.com/CyanogenMod/android_device_samsung_epicmtd

also, perhaps a way to distinguish it from others is the presence of a directly in root named: stage1

This uses bmlovermtd, with the mtd filesystem.

It should be named Epic4G (MTD) or something similar.

Thanks koush!

**Comment by koush** [comment]
yeah, just fixed this.
