### ISSUE TITLE
HTC Wildfire S support

### ISSUE THREAD

**Issue by insink71** [koush/ROMManagerManifest#358]
First of all, thank you so much for your hard work; much respect.  I currently have two Wildfire S devices; which, I would be more than willing to lend alternately [if Rom Manager decided to support the Wildfire S].  I have a Virgin Mobile A510c [marvelc] Wildfire S and a Tmobile A510a [marvel] Wildfire S.  Both are currently running the same recovery [alquez unofficial cwm; thread on xda]; however, I believe his port of the recovery lacks the hooks rom manager needs to recognize the device [thus supporting the rom listing side].  So again, if you would like the devices, I have them and am willing to ship for testing/development purposes [on an alternating basis].  I do not have a marvelct device [asian cdma], but one each of gsm and cdma [US carriers].

Regards.
Rob

**Comment by insink71** [comment]
Recovery link is http://forum.xda-developers.com/showthread.php?t=1213229 .

**Comment by insink71** [comment]
I believe this was built from the with the help of HCDRJacob and his repository https://github.com/HCDRJacob/device_htc_marvel .

**Comment by koush** [comment]
Hi, is the "marvel" device the board name of the Wildfire S? I can use that to build?

**Comment by insink71** [comment]
Yes marvel is the board name; although, wildfire s comes with marvel,
marvelc, and marvelct board variations (last two being cdma).
Alquez's recovery was written for marvel boards but works on the
marvelc boards as well [may also work on marvelct; it's an asian cdma
variant; to which, I do not own a device; thus, I haven't tested].
Mainly wanted to let you know I had a marvel device [A510a Tmobile]
and a marvelc device [A510c Virgin Mobile] I can send you
[alternately] if you need them for building/testing [or I could pull
config.gz's and email you or whatever you might need].  I always
prefer having device in hand for testing over an emulator ;)  I'll
even do shipping [both ways; both devices]; my contribution to the
wildfire s community.  On the cdma / gsm board configs;  The main
difference seems to be rom based [gsm uses radio and lib files; cdma
relies on PRL; etc][recovery cross-compatible and I've seen a cross-compatible kernel];  I got rom manager working except for the rom
side a couple times, but if people download and flash gsm roms to a
cdma phone [or vise-versa] there may be problems [had a lot of that
back in Nov/Dec when the cdma phones came out and ppl tried to flash
gsm roms/RUUs].  The board configs should be split eventually to
noob-proof rom manager if rom support is added.

Thanks,
Rob

**Comment by koush** [comment]
So I built it, but I am getting reports of pink text or something. Can you confirm? It's on ROM Manager.

**Comment by insink71** [comment]
Will confirm today... left gsm wildfire s at work in a drawer.

EDIT: Yep.  It works [the good news :)]; however, the graphics are off and it displays pink & green.  
Alquez wrestled with this early on as I remember... I will wait and see if he joins the discussion and shares how he fixed that challenge.
the marvelc device still shows unsupported device and works with the 3.x.x.x unofficial change you made 
[cdma development is behind; htc unlocked bootloaders but did not release kernel source for cdma devices yet]

Rob

**Comment by insink71** [comment]
Also asked alquez to join discussion since he ported it (in blue) :)

**Comment by insink71** [comment]
Not sure if his patch fixed it... but I tooled around the aforementioned github and did see a patch [not sure if you saw it or used it or if it is what fixed alquez's challenges].  It's in BoardConfig.mk; he added three lines of code as follows:
 # Graphics goes here
 BOARD_EGL_CFG := device/htc/marvel/files/egl.cfg

+BOARD_NO_RGBX_8888 := true
+TARGET_LIBAGL_USE_GRALLOC_COPYBITS := true
+
 # Recovery Portion ...

Sorry, but it's the best I can do without alquez's input as of yet.

Rob

Edit: Almost forgot ::slaps himself:: Here's the link to that patch.
https://github.com/HCDRJacob/device_htc_marvel/tree/patch-1

**Comment by insink71** [comment]
damn you are super fast... v5.0.2.8 boots blue :)
Thank you so much.

**Comment by ghost** [comment]
Well, i've noticed Koush about fully working build few moths ago :)
