### ISSUE TITLE
NeoPhyTe

### ISSUE THREAD

**Issue by NeoPhyTe-x360** [koush/ROMManagerManifest#36]
http://www.wuala.com/NeoPhyTe.x360/Publica/Android/ROM_Manager/neophyte.js

This is my manifest

Thanks!

**Comment by bcrook** [comment]
Its up but there is an error in your manifest.js file. Its likely a comma or something.

**Comment by shawe** [comment]
I say to NeoPhyTe what is wrong on his manifest :)
One more think, public please, I don't remember how to do it free by default.

**Comment by koush** [comment]
Added
