### ISSUE TITLE
Support for HTC Vigor (Rezound)

### ISSUE THREAD

**Issue by JmzTaylor** [koush/ROMManagerManifest#361]
Requesting support for HTC Vigor

https://github.com/utkanos/android_device_htc_vigor

**Comment by ghost** [comment]
Yes please!

**Comment by macpro88** [comment]
Yes Please!

**Comment by xjacobx** [comment]
Yes please!

**Comment by hdokes** [comment]
Not just yes but HELL yes!

**Comment by JmzTaylor** [comment]
Supported now.  THANKS!!
