### ISSUE TITLE
Add WFSDev

### ISSUE THREAD

**Issue by WFSDevTeam** [koush/ROMManagerManifest#362]
Hello Koush,
please add the WfsDev-Team.
Manifest:
http://juniorwebdevs.co.uk/ONeill/developer.js

Thanks!

**Comment by WFSDevTeam** [comment]
know the right manifest is there, but the name is false!!!
In the manifest the name WFSDev Team is set, but my e-mailadress is shown!!!
Right link:
http://clockworkmod.com/rommanager/device/marvel/developer/florian.schmidt.stargatewissen%40g?manifest=http%3A%2F%2Fjuniorwebdevs.co.uk%2FONeill%2Fdev_manifest.js&name=WFSDev%20Team&deviceName=HTC%20Wildfire%20S
false link:
http://clockworkmod.com/rommanager/device/marvel/developer/florian.schmidt.stargatewissen%40g?manifest=http%3A%2F%2Fjuniorwebdevs.co.uk%2FONeill%2Fdev_manifest.js&name=florian.schmidt.stargatewissen%40g&deviceName=HTC%20Wildfire%20S

Please edit fast!

**Comment by WFSDevTeam** [comment]
The code in master manifest:
{
      "developer": "florian.schmidt.stargatewissen@g",
      "free": true,
      "id": "florian.schmidt.stargatewissen@g",
      "manifest": "http://juniorwebdevs.co.uk/ONeill/dev_manifest.js",
      "roms": {
        "marvel": true
      },
      "summary": "florian.schmidt.stargatewissen@gmail.com"
    },
and the right code is:
{
    "developer": "WFSDev Team",
    "free": "true",
    "id": "wfsdev",
    "icon": "http://developer.clockworkmod.com/downloads/4378/331dbe9a7dc996400520da4ef443c76f.png",
    "manifest": "http://juniorwebdevs.co.uk/ONeill/dev_manifest.js",
    "roms": {
        "marvel": "true"
    },
    "summary": "We want to make your marvel better!"
},

**Comment by koush** [comment]
Hello, please use this site:

http://developer.clockworkmod.com

That's how to sign up now!

**Comment by WFSDevTeam** [comment]
I used this site, unhappily every time i go to site again (other browser and other pc, but same google account), the settings are away. And now the name in rom manager is florian.schmidt.stargatewissen@g and the false id too :(

**Comment by ghost** [comment]
and one day more, nothing changed!!!

**Comment by WFSDevTeam** [comment]
Why every time when i edit the developer settings they are not saved. ca. 1 hour later the old settings are restored :(

**Comment by WFSDevTeam** [comment]
Can u please edit the manifest manually please?
we would provide our roms over rom manager with right name and the main thing, with right dev id, so we can provide OTA updates soon.

**Comment by koush** [comment]
Hi @WFSDevTeam I just fixed this bug for you.

**Comment by WFSDevTeam** [comment]
unhappily no ;) See the new issue :)
