### ISSUE TITLE
Rezound CWR Issues

### ISSUE THREAD

**Issue by ghost** [koush/ROMManagerManifest#363]
1.  ROM MGR says Touch version not avail.
2.  Backup from ROM MGR does not run.  Reboots to Recovery, but just sits there.
3.  clockworkmod directory created on internal SD, not external.
4.  Power button is set as back, not select.

**Comment by koush** [comment]
1. SHould be there. Just checked on my rezound.
2. Fixed in newest ROM Manager.
3. You can change this preference in RM Settings.
4. Fixed in newest recovery.
