### ISSUE TITLE
3x same group

### ISSUE THREAD

**Issue by WFSDevTeam** [koush/ROMManagerManifest#364]
Hello koush,
Now our WFSDev Team is listed 3 times!!!
One:
florian.schmidt.stargatewissen@g
second:
WFSDev Team
Third:
WFS S Dev Team

In florian.schmidt.stargatewissen@g the download counter is correct and the stars are correct. The other twice has the same manifest, but now downloads and no stars.
We have only one developer account and can't edit anything. The settings in our account now are:
florian.schmidt.stargatewissen@g
I have edited the settings twice yesterday (maybe that are the both flase entries). We can't edit anything again, bc the system don't save the edited files!!! Please edit is manually and we are fine then. 
If we/you can not fix this problem, we must think about to stop rom manager support (unhappily :()

**Comment by koush** [comment]
Hi, I fixed this this morning. The email you were signing up with was very long and exposed a bug in the developer portal. I have fixed this. Please sign up again and you should be good to go!

**Comment by WFSDevTeam** [comment]
unhappily no :)
See the new issue ;)
