### ISSUE TITLE
Rezound Backup Hangs (edited)

### ISSUE THREAD

**Issue by genebean** [koush/ROMManagerManifest#365]
I have the touch recovery installed on a Rezound.  I initiated a "Backup current ROM" from inside RM and it rebooted into recovery and started backing up but has been sitting at "Backing up system" for long enough to make me think it is hung... any chance you could put some kind of progress dialog in here?  I seem to remember that during this part on my OG Droid that it showed what file was being processed or something (I could easily be mistaken here).

(edit: I see now there is a progress indicator... see notes below for real issue)

**Comment by genebean** [comment]
On what may be a related note, I ended up pulling the battery and initiating the backup from the recovery.  That one seems to default to different storage than what RM defaults to... will post again with results of this attempt.

**Comment by genebean** [comment]
Hung again... the point at which it hangs seems to be on backing up HTCMediaAutoUploadSettings.apk

**Comment by genebean** [comment]
Flashed back to non-touch recovery and it backed up fine. Is there any info I can pull for you to help diagnose what is going on here?

**Comment by koush** [comment]
Try turning on fast backup and restore in rom manager. Let me know if that fixes it.

**Comment by genebean** [comment]
Quick backup and restore did not help.  Also, if I read the discription right, this should have turned of the progress stuff... I still saw the files that were being backed up.  I don't know if it is related or not, but I also cannot get Fix Permissions to run in RM, it says "An error occurred while attempting to run privileged command"

**Comment by koush** [comment]
Ok, this is happening on my rezound too on occassion. Let me try to figure out what is causing it....

**Comment by genebean** [comment]
For the moment I am using AmonRA as my recovery since it seems to be the fav on both droidforums.net and XDA.  Plus, it can install su and superuser for rooting.  I am still interested to see this one get up to par so that I can use the touch version :)
