### ISSUE TITLE
WFSDev again

### ISSUE THREAD

**Issue by WFSDevTeam** [koush/ROMManagerManifest#366]
Hello Koush,
we have the same problem now again :)
We are shown twice in the rom manager.
One with name: "florian.schmidt.stargatewissen@g" and one with name: "WFSDev Team"
The WFSDev Team is the right name, but we want to connect both accounts, the name and the device from WFSDev Team and the stars and downloads from florian.schmidt.stargatewissen@g.
The dev_manifest is in both the same and the right. Please edit this and give me comment ;)

**Comment by koush** [comment]
taking a look now

**Comment by koush** [comment]
Ok, I had to delete those accounts, I think I left some of them around during the first cleanup. I just tested with a long email myself. It seems to be working now. Please sign up again, and let me know if you encounter any issues. Sorry about this. Most people have emails under 32 characters, which was the upper limit on the db which stores the acconts.

**Comment by koush** [comment]
If you sign up again and retain your original developer id and manifest, you will get your comments and ratings back automatically.

**Comment by WFSDevTeam** [comment]
So, i have registered and logged in again. I have edit the settings and saved. Hope, that it will be work now ;)

Thanks for your help. I'm depressive now :P No was a joke! :D

**Comment by koush** [comment]
Please let me know if you encounter any more issues.

**Comment by Prototyp** [comment]
Sorry. I know this thread has been closed but I do not know of unfortunately. Today I got my second HTC Wildfire S A510e and had it unlocked via HTCDev. The flash process from the ClockworkMod 5.0.2.8 has been completed successfully but I get no graphical interface to the ClockworkMod. I ask for urgent help. Thank you!

My software version on the Wildfire S: 2.26.401.3
