### ISSUE TITLE
Issues with official recovery

### ISSUE THREAD

**Issue by JmzTaylor** [koush/ROMManagerManifest#377]
This is on the Wildfire S CDMA.  

With CWM installed CM7 fails to install correctly.  But it is random.  But fails 4 of out 5 times.  Recovery.log is clean with no errors, but first boot is riddled with framework issues.  If I install the unofficial 5.0.2.6 version out there it works everytime no issue.  I tried this with 2 different zips.  Both failing on CWM and both working on the older version.  For what its worth my recovery.log is pasted below.  This is from official when I was getting the errors booting.

http://dl.dropbox.com/u/28491940/recovery.log

**Comment by simonsickle-old** [comment]
I can attest to that. I tried RZR and an unofficial recovery, neither of them created errors on boot. Official recovery did, however. It is off and on, but more times than not its a bad flash. My recovery is clean too. Its exactly the same as the one posted above.
