### ISSUE TITLE
Update checks always fail

### ISSUE THREAD

**Issue by fearphage** [koush/ROMManagerManifest#38]
When I check for a new CyanogenMod nightly, it always says there are no updates. However I can always see a newer nightly in the manifest and available to be downloaded. Since it thinks there isn't an update, it also fails to notify about newer nightlies.

**Comment by fearphage** [comment]
Just in case it's relevant, HTC Evo running CM6.

**Comment by koush** [comment]
#blamechris

**Comment by koush** [comment]
Fixed.
