### ISSUE TITLE
CleanEclair Manifest

### ISSUE THREAD

**Issue by maxill1** [koush/ROMManagerManifest#39]
Can you please add this to the manifest?
Thanks :)
{
        developer: "lyka",
        id: "lmaz",
        summary: "A Senseless and deodexed ROM with clean look and feel",
        manifest: "http://www.lucamazzilli.it/ROMS/lmaz.js",
        free: true,
        roms:
        {
            legend: true
        }
}

**Comment by maxill1** [comment]
Thank you very much for adding, but now the block appears two times: before JagerRom and after JagerRom (maybe my fault, i opened an issue and requested a pull to koush).

**Comment by koush** [comment]
fixed
