### ISSUE TITLE
sound disabling is buggy

### ISSUE THREAD

**Issue by nbraker** [koush/ROMManagerManifest#4]
Under an app called "Quick settings", setting phone ring and notifications to different levels is ignored and instead it sets notifications to the same level as phone ring.  This app worked on stock so I am wondering if the upgrade to blackdroid v9 is affecting the sound level settings.  I'm hoping this is a quick fix for you but its probably not even something you should botherb with.

**Comment by bekriebel** [comment]
ROM Manager code does not affect the system itself. You will need to contact the developer of blackdroid with this issue.
