### ISSUE TITLE
New Addition to Rom Manager

### ISSUE THREAD

**Issue by slayher** [koush/ROMManagerManifest#40]
http://pastebin.com/a6s8cg1r

Thanks!!

**Comment by bcrook** [comment]
There is a problem with your personal manifest. I don't know exactly what but please check it out.

**Comment by slayher** [comment]
Fixed it, but can you update to this please?  Thanks!
http://pastebin.com/3ia5pmma

**Comment by slayher** [comment]
Also, I have the personal manifest setup like the examples, but its not downloading from the "choices" part.  Its showing up to give you the choice, but its not actually downloading the file from choices.  Addons is working

**Comment by slayher** [comment]
Nevermind, I got it all working
Thanks again!
