### ISSUE TITLE
Manifest attached. Please add to manifest list. Clark44.

### ISSUE THREAD

**Issue by atbe** [koush/ROMManagerManifest#408]
ROM manifest: http://sashimi.synmonger.com/Clark44/RM/FreeGS3.js

Developer manifest: http://sashimi.synmonger.com/Clark44/RM/developer.js

Thank you.

**Comment by koush** [comment]
hi, the readme on this repo indicate that the entire signup process is now at http://developer.clockworkmod.com

**Comment by atbe** [comment]
which readme file are you referring to?

**Comment by atbe** [comment]
Also, I used that link you just posted and signed up, and uploaded a build
but it's in the premium section only. That's originally why I wanted to go
directly into the manifest.
On Aug 4, 2012 5:17 AM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by chirayudesai** [comment]
@Clark44 you can still use your own manifest, look [here](http://developer.clockworkmod.com/developer/settings)
