### ISSUE TITLE
Fly manifest

### ISSUE THREAD

**Issue by sebirdman** [koush/ROMManagerManifest#41]
{
    // This is what name you want your ROMs to show up under.
    developer: "birdman",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
    id: "mrbirdman",
    // The display summary. Two lines max.
    summary: "DroidX Roms",
    // The location of the developer's manifest.
    manifest: "http://droid.co/birdman/birdman.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
    roms:
    {
        shadow: true

```
}
```

}

**Comment by koush** [comment]
put this in the free section please bcrook, i am not at a comupter with git at hte moment

**Comment by koush** [comment]
btw, the device name is "droidx", i generally call it by the product name if the board name (mapphone_cdma or whatever) is stupid sounding.
