### ISSUE TITLE
Add Support For LG Optimus Me P350 

### ISSUE THREAD

**Issue by RonGokhale** [koush/ROMManagerManifest#411]
https://github.com/RonGokhle/android_device_lge_p350_recovery

**Comment by keyur2maru** [comment]
Seems Good To Me But @koush  Must Approve :)

**Comment by RonGokhale** [comment]
bump 
now p350 have official cm7 support so now can we have official cwm support too?

**Comment by koush** [comment]
Can I just build the recovery using the official CM repo?

**Comment by RonGokhale** [comment]
yes you can build using official cm repo

**Comment by koush** [comment]
Oh, so then I don't need this repo? I'll just build the CM one. Give me a moment.

**Comment by RonGokhale** [comment]
yes, i created this repo before  getting official support and recovery with official repo  work perfectly

**Comment by RonGokhale** [comment]
bump
koush any news?
