### ISSUE TITLE
Add Support for LGE Optimus 3D Max

### ISSUE THREAD

**Issue by RonGokhale** [koush/ROMManagerManifest#414]
koush can you add official cwm support LGE optimus 3d max.
Repo is here
https://github.com/RonGokhle/android_device_lge_p725
there is 2 branch ics and gingerbread

**Comment by koush** [comment]
hi, can you please create jellybean branches on the two devices you submitted? I'm building the recovery off the jellybean branches in the CM repos. ics has been discontinued.

**Comment by rmcc** [comment]
Koush, don't merge this into CM. This is one of the devices for which I have pending CM9/10 device configs.

**Comment by koush** [comment]
alrighty

**Comment by RonGokhale** [comment]
ok created jellybean branch and deleted gingerbread branch
