### ISSUE TITLE
How to include a recovery in Rom Manager?

### ISSUE THREAD

**Issue by getitnowmarketing** [koush/ROMManagerManifest#42]
I've read your post on how to update roms for Rom Manager but what steps do i need to do to add a recovery?

**Comment by koush** [comment]
http://www.koushikdutta.com/2010/03/rom-manager-and-third-party-roms.html

**Comment by koush** [comment]
Oh, just mail me a link to the recovery, and a name. ROM Manager only supports the 1 alternate recovery per phone.

**Comment by getitnowmarketing** [comment]
Just emailed it thanks for your help.
