### ISSUE TITLE
Add support for LG Optimus L9 (P760)

### ISSUE THREAD

**Issue by markolino631** [koush/ROMManagerManifest#421]
Hi Koush and Ricardo cerquiera,
i'm working on phone in title, it has locked bootloader but i used bootstrap method to boot it!
Now i've got cm9 working (not all but almost) and i'm working to port also cm10 and maybe after cm10.1.
The device source are here: https://github.com/lgics/android_device_lge_p760/tree/ics

i will appreciate your reply :)

**Comment by rmcc** [comment]
Er. I've had that phone running cm10.1 since December... Sorry, but locked bootloader devices don't go into CM anymore; if LG ever publishes an unlock for it, it'll get builds the next day.

**Comment by koush** [comment]
What he said ^

Locked bootloaders and such hacky workarounds are not scenarios I want to officially support
