### ISSUE TITLE
Official Support Jetstream

### ISSUE THREAD

**Issue by JmzTaylor** [koush/ROMManagerManifest#422]
Device folder is below.  Touchscreen recovery won't work as the touchscreen driver in kernel needs a lot of work.  Regular recovery works just fine

http://www.github.com/jmztaylor/android_device_htc_puccinilte_recovery

**Comment by koush** [comment]
any reason you suffix it with _recovery?

**Comment by JmzTaylor** [comment]
To keep it different than my CM repo

**Comment by koush** [comment]
The CM repo should generally support building recovery. Any reason you needed a separate repo?

The recovery should be up now in RM (and available in builder).
