### ISSUE TITLE
everest - Motorola Xoom (GSM) missing

### ISSUE THREAD

**Issue by firefart** [koush/ROMManagerManifest#428]
Currently the device "everest" is missing on Rom Manager. It is the GSM version of the Motorola XOOM Tablet.
Since there is a CM Rom to download for this device, it should be included in Rom Manager:
http://get.cm/?device=everest

Currently everest is detected as the CDMA version of the XOOM (stingray) in Rom Manager, which breaks the update process.

**Comment by gweedo767** [comment]
Added.  Thanks.
