### ISSUE TITLE
Add to Rom Manager - Extras for Droid X & Droid 2

### ISSUE THREAD

**Issue by Beesley** [koush/ROMManagerManifest#47]
Hi koush, let me know what else I need to be able to add and edit build.props for the DroidX and Droid2

Here is my .js

http://beesley.droid.co/beesley.js

**Comment by koush** [comment]
I need your developer listing, not your manifest.

**Comment by Beesley** [comment]
{
    // This is what name you want your ROMs to show up under.
developer: "Beesley's Build.Props",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
id: "Beesley",
    // The display summary. Two lines max.
summary: "All Mods to Date, except LCD Density",
    // The location of the developer's manifest.
manifest: "http://beesley.droid.co/beesley.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
roms:
    {
    sholes: true
    },
}

**Comment by Beesley** [comment]
http://pastebin.com/8Be00SRS

**Comment by koush** [comment]
Done!

**Comment by Beesley** [comment]
Thanks Koush!

**Comment by koush** [comment]
This is supposed to be droid2 and droidx, and not sholes right?

**Comment by Beesley** [comment]
Yes, sorry.  I wasn't exactly sure of the changes that needed to be made.  I checked with a few other people for advice to no avail.  Any help would be greatly appreciated.

**Comment by Beesley** [comment]
My situation is a little bit different considering I'm not doing ROM's, I'm just doing build.props.  So any info I sought out wasn't tailored to my needs.

**Comment by Beesley** [comment]
This is only showing up in Premium Rom Manager.  Is there any way to get it in to the free version?

**Comment by Beesley** [comment]
My summary is wrong.  My mistake.  Could it please be changed to:

All Build.prop Mods to Date
