### ISSUE TITLE
Beesley's Manifest and Summary Change

### ISSUE THREAD

**Issue by Beesley** [koush/ROMManagerManifest#49]
My summary is wrong, my fault.  Could it be changed please?  

http://pastebin.com/0buqDJd3

{
    // This is what name you want your ROMs to show up under.
developer: "Beesley's Build.Props",
    // Your id. This should have no spaces or other funny characters.
    // This would ideally be your Github id, so when you send me your manifest
    // I can verify who you are. But it can be anything really.
id: "Beesley",
    // The display summary. Two lines max.
summary: "All Build.prop Mods to Date",
    // The location of the developer's manifest.
manifest: "http://beesley.droid.co/beesley.js",
    // The list of devices that this developer's ROMs support.
    // If you don't support a device, just don't list it!
roms:
    {
    shadow: true
    },
}

**Comment by koush** [comment]
shadow should be droidx

**Comment by pcmac77** [comment]
koush, would you like me to merge Beesley's addition (but replace "shadow" with "droidx" in roms?

**Comment by koush** [comment]
Sure, just change the summary manually, dont try to merge/pull it.

**Comment by pcmac77** [comment]
Sorry, the push was not quite what I had expected.  I'll fix it soon.

**Comment by pcmac77** [comment]
Looks like the the content of manifest.js is okay, but the commit history got clobbered.  I'm still making the transition from svn to git and not sure what to do now.  Yikes!

**Comment by koush** [comment]
Yes, you force pushed. Please do not do that. That wiped out changes I had made. If you are unsure about what you are doing, please do not make the change.

**Comment by koush** [comment]
Merged and fixed

**Comment by pcmac77** [comment]
So sorry.  Won't happen again.

**Comment by koush** [comment]
No problem, thanks for the help, lemme know if you have any questions
