### ISSUE TITLE
Theme for Rom Manager

### ISSUE THREAD

**Issue by PMilzie** [koush/ROMManagerManifest#5]
{
    developer: "PMilzie",
    id: "PMilzie",
    summary: "HexFusion Theme for Droid CyanogenMod",
    manifest: "http://github.com/PMilzie/HexFusionTheme/blob/master/hexfusion.js",
    roms:
    {
        sholes: true
    },
}

**Comment by koush** [comment]
You are missing a couple closing braces at the end of your javascript at http://github.com/PMilzie/HexFusionTheme/raw/master/hexfusion.js. When you fix that, your ROMs will load!
