### ISSUE TITLE
New rom manager addition

### ISSUE THREAD

**Issue by Andrizoid** [koush/ROMManagerManifest#53]
here is my manifest
http://ken.appfabulo.us/Rom-Manager/rom-manager-manifest.js

and here is my other info
http://ken.appfabulo.us/Rom-Manager/rom-manager-info.js

**Comment by pcmac77** [comment]
I can addd your section to manifest.js, but I see several syntax problems with your http://ken.appfabulo.us/Rom-Manager/rom-manager-manifest.js:
1. missing comma between name and url under addons,
2. orphan comma after addons

There might be others, but those were what I spot for now.

Peter

**Comment by pcmac77** [comment]
ahh, scratch that, looks like you should probably delete the whone addons section since it has nothing

**Comment by Andrizoid** [comment]
alright, i got it worked out. there was supposed to be an addons section, but i didnt add the link. got that fixed and re-checked for syntax and re-uploaded

**Comment by pcmac77** [comment]
Your ROM has been added, but I think there is still a comma after roms->addons->url...

**Comment by Andrizoid** [comment]
fixed that line. 
how long until it will be available on RM?

**Comment by pcmac77** [comment]
Should be immediate.  Did you mean to exclude your entry from "free"?  I think that means your entry shows up only for people with premium license.

**Comment by Andrizoid** [comment]
no i didnt. im using thise guide and it didnt mention anything about free or premium.
http://www.koushikdutta.com/2010/03/rom-manager-and-third-party-roms.html

**Comment by pcmac77** [comment]
Yeah, I know.  I don't know why it was left out in the guide.  Anyway, I added it just now.  See if it show up.

**Comment by Andrizoid** [comment]
its not. i saw a typo. i fixed it but in the manifest its still
            incredible: true,
instead of 
            inc: true,

**Comment by pcmac77** [comment]
oops, I missed that.  Is that what you have, and HTC Incredible?
Just updated manifests.js

**Comment by Andrizoid** [comment]
ya, i forked and requested the pull but i guess you already had it fixed

**Comment by Andrizoid** [comment]
looks like it was fixed on in your fork, in koushs manifest its still reading as incredible: true,
