### ISSUE TITLE
New Incredible ROM to ROM Manager

### ISSUE THREAD

**Issue by brucekey** [koush/ROMManagerManifest#56]
I have just released "Uncommon Sense" for the incredible. The manifest has been created. http://www.pcjock.com/uncommon/rommanager_uncommonsense.js

Let me know if you need anything else. Thanks!

**Comment by pcmac77** [comment]
I added your entry while setting it as a free ROM.  Also, I noticed a trailing comma on line 36 in http://www.pcjock.com/uncommon/ROMManagerManifest/uncommon.js.  Please remove it.

Peter

**Comment by koush** [comment]
closing issue as this was added
