### ISSUE TITLE
alternate recovery links for ally and incredible

### ISSUE THREAD

**Issue by getitnowmarketing** [koush/ROMManagerManifest#59]
{
        init: "init.inc.rc",
        key: "inc",
        name: "HTC Incredible (CDMA)",
        version: "2.5.0.5",
        readonly_recovery: true
    {
            name: "RA_GNM Recovery v1.7.6",
            url: "http://www.getitnowmarketing.noodlesoftware.com/recovery/recovery-RA-inc_v1.7.0.6_GNM.img"
        }
    },

{
        init: "init.aloha.rc",
        key: "aloha",
        name: "LG Ally",
        version: "2.5.0.5"
    alternate_recovery:
        {
            name: "RA_GNM Recovery v1.2.4",
            url: "http://www.getitnowmarketing.noodlesoftware.com/recovery/recovery-aloha-RA_GNM_v1.2.4.img"
        }
    },

**Comment by pcmac77** [comment]
Hi Koushik, or anyone else who knows...

I have made changes to devices.js to add the above changes (while correcting some obvious syntactical errors.  I have committed only to my branch at this point pending input from you guys.  Here's the link to my commit:
http://github.com/pcmac77/ROMManagerManifest/commit/1f8a8a5095db2e82d8b49d0bb00f6f236df60672

Looking at rommanager.js, I see how the key-value pairs are used, but it isn't clear to me why.

I also see that devices2.js has a diffferent syntax, which rommanager.js actually references.  Does this file need to be updated as well?

Anyway, I don't mean to add extra work for Koushik or anyone else, it's more of satisfying my curiosity, I suppose.  I apologize if information pertaining to my questions have already been documented elsewhere.  In that case, please kindly point me to it, and I'll read up.  

Alternatively, if it just takes too much time to respond, feel free to ignore my message and update the necessary files.  I'm sure seeing how the file(s) is/are updated, I can at least get some of my questions answered.

Thanks.

Peter

**Comment by getitnowmarketing** [comment]
any update on this being added?

**Comment by koush** [comment]
Inc is still using fakeflash, so the .img won't work. Let me talk to the unrevoked guys and see what the state of that is.

**Comment by koush** [comment]
I think this was done.
