### ISSUE TITLE
Update manifest.js

### ISSUE THREAD

**Issue by crunchysoft** [koush/ROMManagerManifest#73]
Hey, The original issue is closed but just want to update my manifest.js to include another device and change the summary.
    {
        developer: "CrunchySoft",
        id: "crunchybutternut",
        summary: "Fast and fully themed ROMs for the CDMA Hero/HTC Evo by crunchybutternut.",
        free: true,
        manifest: "http://crunchysoft.pocketdevelopers.com/ROMManagerManifest/crunchysoft.js",
        roms:
        {
            heroc: true,
            supersonic: true,
        }
    }

Thanks!

**Comment by pcmac77** [comment]
done
